export const ADDRESS_CREATE_REQUEST = "ADDRESS_CREATE_REQUEST";
export const ADDRESS_CREATE_SUCCESS = "ADDRESS_CREATE_SUCCESS";
export const ADDRESS_CREATE_FAIL = "ADDRESS_CREATE_FAIL";

export const ADDRESS_LIST_REQUEST = "ADDRESS_LIST_REQUEST";
export const ADDRESS_LIST_SUCCESS = "ADDRESS_LIST_SUCCESS";
export const ADDRESS_LIST_FAIL = "ADDRESS_LIST_FAIL";
export const ADDRESS_DETAILS_RESET = "ADDRESS_DETAILS_RESET";
export const CUS_LIST_REQUEST = "CUS_LIST_REQUEST";
export const CUS_LIST_SUCCESS = "CUS_LIST_SUCCESS";
export const CUS_LIST_FAIL = "CUS_LIST_FAIL";
export const CUS_LIST_RESET = "CUS_LIST_RESET";
