export const APPLICATION_SETTING_REQUEST = 'APPLICATION_SETTING_REQUEST';
export const APPLICATION_SETTING_SUCCESS = 'APPLICATION_SETTING_SUCCESS';
export const APPLICATION_SETTING_FAIL = 'APPLICATION_SETTING_SAVE';
export const APPLICATION_SETTING_RESET = 'APPLICATION_SETTING_RESET';

export const APPLICATION_SETTING_LIST_REQUEST = 'APPLICATION_SETTING_LIST_REQUEST';
export const APPLICATION_SETTING_LIST_SUCCESS = 'APPLICATION_SETTING_LIST_SUCCESS';
export const APPLICATION_SETTING_LIST_FAIL = 'APPLICATION_SETTING_LIST_FAIL';

export const APPLICATION_DELETE_REQUEST = 'APPLICATION_DELETE_REQUEST';
export const APPLICATION_DELETE_SUCCESS = 'APPLICATION_DELETE_SUCCESS';
export const APPLICATION_DELETE_FAIL = 'APPLICATION_DELETE_FAIL';
export const APPLICATION_DELETE_RESET = 'APPLICATION_DELETE_RESET';

export const APPLICATION_ENABLE_UPDATE_REQUEST = 'APPLICATION_ENABLE_UPDATE_REQUEST';
export const APPLICATION_ENABLE_UPDATE_SUCCESS = 'APPLICATION_ENABLE_UPDATE_SUCCESS';
export const APPLICATION_ENABLE_UPDATE_FAIL = 'APPLICATION_ENABLEUPDATE_FAIL';
export const APPLICATION_ENABLE_UPDATE_RESET = 'APPLICATION_ENABLE_UPDATE_RESET';
