export const ATTRIBUTE_CREATE_REQUEST = "ATTRIBUTE_CREATE_REQUEST";
export const ATTRIBUTE_CREATE_SUCCESS = "ATTRIBUTE_CREATE_SUCCESS";
export const ATTRIBUTE_CREATE_FAIL = "ATTRIBUTE_CREATE_FAIL";
export const ATTRIBUTE_CREATE_RESET = "ATTRIBUTE_CREATE_RESET";

export const ATTRIBUTE_LIST_REQUEST = "ATTRIBUTE_LIST_REQUEST";
export const ATTRIBUTE_LIST_SUCCESS = "ATTRIBUTE_LIST_SUCCESS";
export const ATTRIBUTE_LIST_FAIL = "ATTRIBUTE_LIST_FAIL";

export const ATTRIBUTE_VALUE_CREATE_REQUEST = "ATTRIBUTE_VALUE_CREATE_REQUEST";
export const ATTRIBUTE_VALUE_CREATE_SUCCESS = "ATTRIBUTE_VALUE_CREATE_SUCCESS";
export const ATTRIBUTE_VALUE_CREATE_FAIL = "ATTRIBUTE_VALUE_CREATE_FAIL";
export const ATTRIBUTE_VALUE_CREATE_RESET = "ATTRIBUTE_VALUE_CREATE_RESET";

export const ATTRIBUTE_VALUE_LIST_REQUEST = "ATTRIBUTE_VALUE_LIST_REQUEST";
export const ATTRIBUTE_VALUE_LIST_SUCCESS = "ATTRIBUTE_VALUE_LIST_SUCCESS";
export const ATTRIBUTE_VALUE_LIST_FAIL = "ATTRIBUTE_VALUE_LIST_FAIL";
export const ATTRIBUTE_VALUEALL_LIST_REQUEST = "ATTRIBUTE_VALUEALL_LIST_REQUEST";
export const ATTRIBUTE_VALUEALL_LIST_SUCCESS = "ATTRIBUTE_VALUEALL_LIST_SUCCESS";
export const ATTRIBUTE_VALUEALL_LIST_FAIL = "ATTRIBUTE_VALUEALL_LIST_FAIL";


export const FEATURES_CREATE_REQUEST = "FEATURES_CREATE_REQUEST";
export const FEATURES_CREATE_SUCCESS = "FEATURES_CREATE_SUCCESS";
export const FEATURES_CREATE_FAIL = "FEATURES_CREATE_FAIL";
export const FEATURES_CREATE_RESET = "FEATURES_CREATE_RESET";

export const FEATURES_LIST_REQUEST = "FEATURES_LIST_REQUEST";
export const FEATURES_LIST_SUCCESS = "FEATURES_LIST_SUCCESS";
export const FEATURES_LIST_FAIL = "FEATURES_LIST_FAIL";

export const FEATURES_VALUE_CREATE_REQUEST = "FEATURES_VALUE_CREATE_REQUEST";
export const FEATURES_VALUE_CREATE_SUCCESS = "FEATURES_VALUE_CREATE_SUCCESS";
export const FEATURES_VALUE_CREATE_FAIL = "FEATURES_VALUE_CREATE_FAIL";
export const FEATURES_VALUE_CREATE_RESET = "FEATURES_VALUE_CREATE_RESET";

export const FEATURES_VALUE_LIST_REQUEST = "FEATURES_VALUE_LIST_REQUEST";
export const FEATURES_VALUE_LIST_SUCCESS = "FEATURES_VALUE_LIST_SUCCESS";
export const FEATURES_VALUE_LIST_FAIL = "FEATURES_VALUE_LIST_FAIL";

export const ATTRIBUTE_UPDATE_REQUEST = 'ATTRIBUTE_UPDATE_REQUEST';
export const ATTRIBUTE_UPDATE_SUCCESS = 'ATTRIBUTE_UPDATE_SUCCESS';
export const ATTRIBUTE_UPDATE_FAIL = 'ATTRIBUTE_UPDATE_FAIL';
export const ATTRIBUTE_UPDATE_RESET = 'ATTRIBUTE_UPDATE_RESET';

export const ATTRIBUTE_DELETE_REQUEST = 'ATTRIBUTE_DELETE_REQUEST';
export const ATTRIBUTE_DELETE_SUCCESS = 'ATTRIBUTE_DELETE_SUCCESS';
export const ATTRIBUTE_DELETE_FAIL = 'ATTRIBUTE_DELETE_FAIL';
export const ATTRIBUTE_DELETE_RESET = 'ATTRIBUTE_DELETE_RESET';

export const ATTRIBUTE_VALUE_UPDATE_REQUEST = 'ATTRIBUTE_VALUE_UPDATE_REQUEST';
export const ATTRIBUTE_VALUE_UPDATE_SUCCESS = 'ATTRIBUTE_VALUE_UPDATE_SUCCESS';
export const ATTRIBUTE_VALUE_UPDATE_FAIL = 'ATTRIBUTE_VALUE_UPDATE_FAIL';
export const ATTRIBUTE_VALUE_UPDATE_RESET = 'ATTRIBUTE_VALUE_UPDATE_RESET';

export const ATTRIBUTE_VALUE_DELETE_REQUEST = 'ATTRIBUTE_VALUE_DELETE_REQUEST';
export const ATTRIBUTE_VALUE_DELETE_SUCCESS = 'ATTRIBUTE_VALUE_DELETE_SUCCESS';
export const ATTRIBUTE_VALUE_DELETE_FAIL = 'ATTRIBUTE_VALUE_DELETE_FAIL';
export const ATTRIBUTE_VALUE_DELETE_RESET = 'ATTRIBUTE_VALUE_DELETE_RESET';

// ************************Feature section****************************

export const FEATURES_UPDATE_REQUEST = 'FEATURES_UPDATE_REQUEST';
export const FEATURES_UPDATE_SUCCESS = 'FEATURES_UPDATE_SUCCESS';
export const FEATURES_UPDATE_FAIL = 'FEATURES_UPDATE_FAIL';
export const FEATURES_UPDATE_RESET = 'FEATURES_UPDATE_RESET';

export const FEATURES_DELETE_REQUEST = 'FEATURES_DELETE_REQUEST';
export const FEATURES_DELETE_SUCCESS = 'FEATURES_DELETE_SUCCESS';
export const FEATURES_DELETE_FAIL = 'FEATURES_DELETE_FAIL';
export const FEATURES_DELETE_RESET = 'FEATURES_DELETE_RESET';

export const FEATURES_VALUE_UPDATE_REQUEST = 'FEATURES_VALUE_UPDATE_REQUEST';
export const FEATURES_VALUE_UPDATE_SUCCESS = 'FEATURES_VALUE_UPDATE_SUCCESS';
export const FEATURES_VALUE_UPDATE_FAIL = 'FEATURES_VALUE_UPDATE_FAIL';
export const FEATURES_VALUE_UPDATE_RESET = 'FEATURES_VALUE_UPDATE_RESET';

export const FEATURES_VALUE_DELETE_REQUEST = 'FEATURES_VALUE_DELETE_REQUEST';
export const FEATURES_VALUE_DELETE_SUCCESS = 'FEATURES_VALUE_DELETE_SUCCESS';
export const FEATURES_VALUE_DELETE_FAIL = 'FEATURES_VALUE_DELETE_FAIL';
export const FEATURES_VALUE_DELETE_RESET = 'FEATURES_VALUE_DELETE_RESET';


// *****************************************
export const ATTRIBUTE_ACTIVE_UPDATE_REQUEST = 'ATTRIBUTE_ACTIVE_UPDATE_REQUEST';
export const ATTRIBUTE_ACTIVE_UPDATE_SUCCESS = 'ATTRIBUTE_ACTIVE_UPDATE_SUCCESS';
export const ATTRIBUTE_ACTIVE_UPDATE_FAIL = 'ATTRIBUTE_ACTIVE_UPDATE_FAIL';
export const ATTRIBUTE_ACTIVE_UPDATE_RESET = 'ATTRIBUTE_ACTIVE_UPDATE_RESET';

export const ATTRIBUTE_VALUE_ACTIVE_UPDATE_REQUEST = 'ATTRIBUTE_VALUE_ACTIVE_UPDATE_REQUEST';
export const ATTRIBUTE_VALUE_ACTIVE_UPDATE_SUCCESS = 'ATTRIBUTE_VALUE_ACTIVE_UPDATE_SUCCESS';
export const ATTRIBUTE_VALUE_ACTIVE_UPDATE_FAIL = 'ATTRIBUTE_VALUE_ACTIVE_UPDATE_FAIL';
export const ATTRIBUTE_VALUE_ACTIVE_UPDATE_RESET = 'ATTRIBUTE_VALUE_ACTIVE_UPDATE_RESET';


export const FEATURES_ACTIVE_UPDATE_REQUEST = 'ATTRIBUTE_ACTIVE_UPDATE_REQUEST';
export const FEATURES_ACTIVE_UPDATE_SUCCESS = 'ATTRIBUTE_ACTIVE_UPDATE_SUCCESS';
export const FEATURES_ACTIVE_UPDATE_FAIL = 'ATTRIBUTE_ACTIVE_UPDATE_FAIL';
export const FEATURES_ACTIVE_UPDATE_RESET = 'ATTRIBUTE_ACTIVE_UPDATE_RESET';

export const FEATURES_VALUE_ACTIVE_UPDATE_REQUEST = 'FEATURES_VALUE_ACTIVE_UPDATE_REQUEST';
export const FEATURES_VALUE_ACTIVE_UPDATE_SUCCESS = 'FEATURES_VALUE_ACTIVE_UPDATE_SUCCESS';
export const FEATURES_VALUE_ACTIVE_UPDATE_FAIL = 'FEATURES_VALUE_ACTIVE_UPDATE_FAIL';
export const FEATURES_VALUE_ACTIVE_UPDATE_RESET = 'FEATURES_VALUE_ACTIVE_UPDATE_RESET';

// ********************************************************************************************
export const ATTRIBUTE_ENABLE_UPDATE_REQUEST = 'ATTRIBUTE_ENABLE_UPDATE_REQUEST';
export const ATTRIBUTE_ENABLE_UPDATE_SUCCESS = 'ATTRIBUTE_ENABLE_UPDATE_SUCCESS';
export const ATTRIBUTE_ENABLE_UPDATE_FAIL = 'ATTRIBUTE_ENABLEUPDATE_FAIL';
export const ATTRIBUTE_ENABLE_UPDATE_RESET = 'ATTRIBUTE_ENABLE_UPDATE_RESET';


export const ATTRIBUTE_VALUE_ENABLE_UPDATE_REQUEST = 'ATTRIBUTE_VALUE_ENABLE_UPDATE_REQUEST';
export const ATTRIBUTE_VALUE_ENABLE_UPDATE_SUCCESS = 'ATTRIBUTE_VALUE_ENABLE_UPDATE_SUCCESS';
export const ATTRIBUTE_VALUE_ENABLE_UPDATE_FAIL = 'ATTRIBUTE_VALUE_ENABLEUPDATE_FAIL';
export const ATTRIBUTE_VALUE_ENABLE_UPDATE_RESET = 'ATTRIBUTE_VALUE_ENABLE_UPDATE_RESET';

export const FEATURES_ENABLE_UPDATE_REQUEST = 'FEATURES_ENABLE_UPDATE_REQUEST';
export const FEATURES_ENABLE_UPDATE_SUCCESS = 'FEATURES_ENABLE_UPDATE_SUCCESS';
export const FEATURES_ENABLE_UPDATE_FAIL = 'FEATURES_ENABLEUPDATE_FAIL';
export const FEATURES_ENABLE_UPDATE_RESET = 'FEATURES_ENABLE_UPDATE_RESET';

export const FEATURES_VALUE_ENABLE_UPDATE_REQUEST = 'FEATURES_VALUE_ENABLE_UPDATE_REQUEST';
export const FEATURES_VALUE_ENABLE_UPDATE_SUCCESS = 'FEATURES_VALUE_ENABLE_UPDATE_SUCCESS';
export const FEATURES_VALUE_ENABLE_UPDATE_FAIL = 'FEATURES_VALUE_ENABLEUPDATE_FAIL';
export const FEATURES_VALUE_ENABLE_UPDATE_RESET = 'FEATURES_VALUE_ENABLE_UPDATE_RESET';

export const ATTRIBUTE_MULTIPLE_DELETE_REQUEST = 'ATTRIBUTE_MULTIPLE_DELETE_REQUEST';
export const ATTRIBUTE_MULTIPLE_DELETE_SUCCESS = 'ATTRIBUTE_MULTIPLE_DELETE_SUCCESS';
export const ATTRIBUTE_MULTIPLE_DELETE_FAIL = 'ATTRIBUTE_MULTIPLE_DELETE_FAIL';
export const ATTRIBUTE_MULTIPLE_DELETE_RESET = 'ATTRIBUTE_MULTIPLE_DELETE_RESET';


export const ATTRIBUTE_VALUE_MULTIPLE_DELETE_REQUEST = 'ATTRIBUTE_VALUE_MULTIPLE_DELETE_REQUEST';
export const ATTRIBUTE_VALUE_MULTIPLE_DELETE_SUCCESS = 'ATTRIBUTE_VALUE_MULTIPLE_DELETE_SUCCESS';
export const ATTRIBUTE_VALUE_MULTIPLE_DELETE_FAIL = 'ATTRIBUTE_VALUE_MULTIPLE_DELETE_FAIL';
export const ATTRIBUTE_VALUE_MULTIPLE_DELETE_RESET = 'ATTRIBUTE_VALUE_MULTIPLE_DELETE_RESET';

export const FEATURES_MULTIPLE_DELETE_REQUEST = 'FEATURES_MULTIPLE_DELETE_REQUEST';
export const FEATURES_MULTIPLE_DELETE_SUCCESS = 'FEATURES_MULTIPLE_DELETE_SUCCESS';
export const FEATURES_MULTIPLE_DELETE_FAIL = 'FEATURES_MULTIPLE_DELETE_FAIL';
export const FEATURES_MULTIPLE_DELETE_RESET = 'FEATURES_MULTIPLE_DELETE_RESET';

export const FEATURES_VALUE_MULTIPLE_DELETE_REQUEST = 'FEATURES_VALUE_MULTIPLE_DELETE_REQUEST';
export const FEATURES_VALUE_MULTIPLE_DELETE_SUCCESS = 'FEATURES_VALUE_MULTIPLE_DELETE_SUCCESS';
export const FEATURES_VALUE_MULTIPLE_DELETE_FAIL = 'FEATURES_VALUE_MULTIPLE_DELETE_FAIL';
export const FEATURES_VALUE_MULTIPLE_DELETE_RESET = 'FEATURES_VALUE_MULTIPLE_DELETE_RESET';




