export const BRAND_REQUEST = 'BRAND_REQUEST';
export const BRAND_SUCCESS = 'BRAND_SUCCESS';
export const BRAND_FAIL = 'BRAND_FAIL';
export const BRAND_RESET = 'BRAND_RESET';

export const BRAND_SAVE_REQUEST = 'BRAND_SAVE_REQUEST';
export const BRAND_SAVE_SUCCESS = 'BRAND_SAVE_SUCCESS';
export const BRAND_SAVE_FAIL = 'BRAND_SAVE_FAIL';
export const BRAND_SAVE_RESET = 'BRAND_SAVE_RESET';

export const BRAND_UPDATE_REQUEST = 'BRAND_UPDATE_REQUEST';
export const BRAND_UPDATE_SUCCESS = 'BRAND_UPDATE_SUCCESS';
export const BRAND_UPDATE_FAIL = 'BRAND_UPDATE_FAIL';
export const BRAND_UPDATE_RESET = 'BRAND_UPDATE_RESET';

export const BRAND_DELETE_REQUEST = 'BRAND_DELETE_REQUEST';
export const BRAND_DELETE_SUCCESS = 'BRAND_DELETE_SUCCESS';
export const BRAND_DELETE_FAIL = 'BRAND_DELETE_FAIL';
export const BRAND_DELETE_RESET = 'BRAND_DELETE_RESET';

export const BRAND_ADDRESS_REQUEST = 'BRAND_ADDRESS_REQUEST';
export const BRAND_ADDRESS_SUCCESS = 'BRAND_ADDRESS_SUCCESS';
export const BRAND_ADDRESS_FAIL = 'BRAND_ADDRESS_FAIL';
export const BRAND_ADDRESS_RESET = 'BRAND_ADDRESS_RESET';

export const BRAND_ADDRESS_UPDATE_REQUEST = 'BRAND_ADDRESS_UPDATE_REQUEST';
export const BRAND_ADDRESS_UPDATE_SUCCESS = 'BRAND_ADDRESS_UPDATE_SUCCESS';
export const BRAND_ADDRESS_UPDATE_FAIL = 'BRAND_ADDRESS_UPDATE_FAIL';
export const BRAND_ADDRESS_UPDATE_RESET = 'BRAND_ADDRESS_UPDATE_RESET';


export const BRAND_UPDATES_REQUEST = 'BRAND_UPDATES_REQUEST';
export const BRAND_UPDATES_SUCCESS = 'BRAND_UPDATES_SUCCESS';
export const BRAND_UPDATES_FAIL = 'BRAND_UPDATES_FAIL';
export const BRAND_UPDATES_RESET = 'BRAND_UPDATES_RESET';

export const BRAND_ENABLE_UPDATE_REQUEST = 'BRAND_ENABLE_UPDATE_REQUEST';
export const BRAND_ENABLE_UPDATE_SUCCESS = 'BRAND_ENABLE_UPDATE_SUCCESS';
export const BRAND_ENABLE_UPDATE_FAIL = 'BRAND_ENABLEUPDATE_FAIL';
export const BRAND_ENABLE_UPDATE_RESET = 'BRAND_ENABLE_UPDATE_RESET';


export const BRAND_MULTIPLE_DELETE_REQUEST = 'BRAND_MULTIPLE_DELETE_REQUEST';
export const BRAND_MULTIPLE_DELETE_SUCCESS = 'BRAND_MULTIPLE_DELETE_SUCCESS';
export const BRAND_MULTIPLE_DELETE_FAIL = 'BRAND_MULTIPLE_DELETE_FAIL';
export const BRAND_MULTIPLE_DELETE_RESET = 'BRAND_MULTIPLE_DELETE_RESET';
