export const CART_ADD_ITEM = 'CART_ADD_ITEM';
export const CART_REMOVE_ITEM = 'CART_REMOVE_ITEM';
export const CART_SAVE_SHIPPING_ADDRESS = 'CART_SAVE_SHIPPING_ADDRESS';
export const CART_SAVE_PAYMENT_METHOD = 'CART_SAVE_PAYMENT_METHOD';
export const CART_EMPTY = 'CART_EMPTY';
export const CART_ADD_ITEM_FAIL = 'CART_ADD_ITEM_FAIL';

export const USER_CART_LIST_REQUST = 'USER_CART_LIST_REQUST';
export const USER_CART_LIST_SUCCESS = 'USER_CART_LIST_SUCCESS';
export const USER_CART_LIST_FAIL = 'USER_CART_LIST_FAIL';

export const CART_DELETE_REQUEST ="CART_DELETE_REQUEST";
export const CART_DELETE_FAIL="CART_DELETE_FAIL";
export const CART_DELETE_SUCCESS="CART_DELETE_SUCCESS";
export const CART_DELETE_RESET ="CART_DELETE_RESET"

export const  USER_CART_ID_SUCCESS ="USER_CART_ID_SUCCESS";
export const  USER_CART_ID_FAIL ="USER_CART_ID_FAIL";
export const  USER_CART_ID_REQUST ="USER_CART_ID_REQUST";

export const  CART_UPDATE_REQUEST = "CART_UPDATE_REQUEST";
export const  CART_UPDATE_SUCCESS ="CART_UPDATE_SUCCESS";
export const  CART_UPDATE_FAIL ="CART_UPDATE_FAIL";
export const  CART_UPDATE_RESET = "CART_UPDATE_RESET";

export const CART_CREATE_REQUEST ="CART_CREATE_REQUEST";
export const CART_CREATE_SUCCESS="CART_CREATE_SUCCESS";
export const CART_CREATE_FAIL="CART_CREATE_FAIL";

