export const CAT_PRODUCT_REQUEST = 'CAT_PRODUCT_REQUEST';
export const CAT_PRODUCT_SUCCESS = 'CAT_PRODUCT_SUCCESS';
export const CAT_PRODUCT_FAIL = 'CAT_PRODUCT_FAIL';
export const CAT_PRODUCT_RESET = 'CAT_PRODUCT_RESET';

export const CAT_PRODUCT_SAVE_REQUEST = 'CAT_PRODUCT_SAVE_REQUEST';
export const CAT_PRODUCT_SAVE_SUCCESS = 'CAT_PRODUCT_SAVE_SUCCESS';
export const CAT_PRODUCT_SAVE_FAIL = 'CAT_PRODUCT_SAVE_FAIL';
export const CAT_PRODUCT_SAVE_RESET = 'CAT_PRODUCT_SAVE_RESET';

export const CAT_PRODUCT_UPDATE_REQUEST = 'CAT_PRODUCT_UPDATE_REQUEST';
export const CAT_PRODUCT_UPDATE_SUCCESS = 'CAT_PRODUCT_UPDATE_SUCCESS';
export const CAT_PRODUCT_UPDATE_FAIL = 'CAT_PRODUCT_UPDATE_FAIL';
export const CAT_PRODUCT_UPDATE_RESET = 'CAT_PRODUCT_UPDATE_RESET';

export const CAT_PRODUCT_DELETE_REQUEST = 'CAT_PRODUCT_DELETE_REQUEST';
export const CAT_PRODUCT_DELETE_SUCCESS = 'CAT_PRODUCT_DELETE_SUCCESS';
export const CAT_PRODUCT_DELETE_FAIL = 'CAT_PRODUCT_DELETE_FAIL';
export const CAT_PRODUCT_DELETE_RESET = 'CAT_PRODUCT_DELETE_RESET';

export const CAT_PRODUCT_DETAILS_REQUEST = 'CAT_PRODUCT_DETAILS_REQUEST';
export const CAT_PRODUCT_DETAILS_SUCCESS = 'CAT_PRODUCT_DETAILS_SUCCESS';
export const CAT_PRODUCT_DETAILS_FAIL = 'CAT_PRODUCT_DETAILS_FAIL';
export const CAT_PRODUCT_DETAILS_RESET = 'CAT_PRODUCT_DETAILS_RESET';

export const WISHLIST_UPDATE_REQUEST = 'WISHLIST_UPDATE_REQUEST';
export const WISHLIST_UPDATE_SUCCESS = 'WISHLIST_UPDATE_SUCCESS';
export const WISHLIST_UPDATE_FAIL = 'WISHLIST_UPDATE_FAIL';
export const WISHLIST_UPDATE_RESET = 'WISHLIST_UPDATE_RESET';


export const COMBINATION_SAVE_REQUEST = 'COMBINATION_SAVE_REQUEST';
export const COMBINATION_SAVE_SUCCESS = 'COMBINATION_SAVE_SUCCESS';
export const COMBINATION_SAVE_FAIL = 'COMBINATION_SAVE_FAIL';
export const COMBINATION_SAVE_RESET = 'COMBINATION_SAVE_RESET';

export const COMBINATION_LIST_REQUEST = 'COMBINATION_LIST_REQUEST';
export const COMBINATION_LIST_SUCCESS = 'COMBINATION_LIST_SUCCESS';
export const COMBINATION_LIST_FAIL = 'COMBINATION_LIST_FAIL';
export const COMBINATION_LIST_RESET = 'COMBINATION_LIST_RESET';


export const COMBINATION_CHILD_LIST_REQUEST = 'COMBINATION_CHILD_LIST_REQUEST';
export const COMBINATION_CHILD_LIST_SUCCESS = 'COMBINATION_CHILD_LIST_SUCCESS';
export const COMBINATION_CHILD_LIST_FAIL = 'COMBINATION_CHILD_LIST_FAIL';
export const COMBINATION_CHILD_LIST_RESET = 'COMBINATION_CHILD_LIST_RESET';

export const COMBINATION_UPDATE_REQUEST = 'COMBINATION_UPDATE_REQUEST';
export const COMBINATION_UPDATE_SUCCESS = 'COMBINATION_UPDATE_SUCCESS';
export const COMBINATION_UPDATE_FAIL = 'COMBINATION_UPDATE_FAIL';
export const COMBINATION_UPDATE_RESET = 'COMBINATION_UPDATE_RESET';

export const CAT_PRODUCT_ACTIVE_UPDATE_REQUEST = 'CAT_PRODUCT_ACTIVE_UPDATE_REQUEST';
export const CAT_PRODUCT_ACTIVE_UPDATE_SUCCESS = 'CAT_PRODUCT_ACTIVE_UPDATE_SUCCESS';
export const CAT_PRODUCT_ACTIVE_UPDATE_FAIL = 'CAT_PRODUCT_ACTIVE_UPDATE_FAIL';
export const CAT_PRODUCT_ACTIVE_UPDATE_RESET = 'CAT_PRODUCT_ACTIVE_UPDATE_RESET';

export const PRODUCT_ENABLE_UPDATE_REQUEST = 'PRODUCT_ENABLE_UPDATE_REQUEST';
export const PRODUCT_ENABLE_UPDATE_SUCCESS = 'PRODUCT_ENABLE_UPDATE_SUCCESS';
export const PRODUCT_ENABLE_UPDATE_FAIL = 'PRODUCT_ENABLEUPDATE_FAIL';
export const PRODUCT_ENABLE_UPDATE_RESET = 'PRODUCT_ENABLE_UPDATE_RESET';


export const PRODUCT_MULTIPLE_DELETE_REQUEST = 'PRODUCT_MULTIPLE_DELETE_REQUEST';
export const PRODUCT_MULTIPLE_DELETE_SUCCESS = 'PRODUCT_MULTIPLE_DELETE_SUCCESS';
export const PRODUCT_MULTIPLE_DELETE_FAIL = 'PRODUCT_MULTIPLE_DELETE_FAIL';
export const PRODUCT_MULTIPLE_DELETE_RESET = 'PRODUCT_MULTIPLE_DELETE_RESET';

export const CAT_PRODUCT_VIEW_REQUEST = 'CAT_PRODUCT_VIEW_REQUEST';
export const CAT_PRODUCT_VIEW_SUCCESS = 'CAT_PRODUCT_VIEW_SUCCESS';
export const CAT_PRODUCT_VIEW_FAIL = 'CAT_PRODUCT_VIEW_FAIL';
export const CAT_PRODUCT_VIEW_RESET = 'CAT_PRODUCT_VIEW_RESET';

export const IMAGE_DELETE_REQUEST = 'IMAGE_DELETE_REQUEST';
export const IMAGE_DELETE_SUCCESS = 'IMAGE_DELETE_SUCCESS';
export const IMAGE_DELETE_FAIL = 'IMAGE_DELETE_FAIL';

export const CAT_LAST_PRODUCT_REQUEST = 'CAT_LAST_PRODUCT_REQUEST';
export const CAT_LAST_PRODUCT_SUCCESS = 'CAT_LAST_PRODUCT_SUCCESS';
export const CAT_LAST_PRODUCT_FAIL = 'CAT_LAST_PRODUCT_FAIL';
export const CAT_LAST_PRODUCT_RESET = 'CAT_LAST_PRODUCT_RESET';

