export const CATEGORY_CREATE_REQUEST = "CATEGORY_CREATE_REQUEST";
export const CATEGORY_CREATE_SUCCESS = "CATEGORY_CREATE_SUCCESS";
export const CATEGORY_CREATE_FAIL = "CATEGORY_CREATE_FAIL";
export const CATEGORY_CREATE_RESET = "CATEGORY_CREATE_RESET";

export const CATEGORY_LIST_REQUEST = "CATEGORY_LIST_REQUEST";
export const CATEGORY_LIST_SUCCESS = "CATEGORY_LIST_SUCCESS";
export const CATEGORY_LIST_FAIL = "CATEGORY_LIST_FAIL";


export const CATEGORY_MASTER_CREATE_REQUEST = "CATEGORY_MASTER_CREATE_REQUEST";
export const CATEGORY_MASTER_CREATE_SUCCESS = "CATEGORY_MASTER_CREATE_SUCCESS";
export const CATEGORY_MASTER_CREATE_FAIL = "CATEGORY_MASTER_CREATE_FAIL";
export const CATEGORY_MASTER_CREATE_RESET = "CATEGORY_MASTER_CREATE_RESET";

export const CATEGORY_MASTER_LIST_REQUEST = "CATEGORY_MASTER_LIST_REQUEST";
export const CATEGORY_MASTER_LIST_SUCCESS = "CATEGORY_MASTER_LIST_SUCCESS";
export const CATEGORY_MASTER_LIST_FAIL = "CATEGORY_MASTER_LIST_FAIL";

export const CATEGORY_SUB_CREATE_REQUEST = "CATEGORY_SUB_CREATE_REQUEST";
export const CATEGORY_SUB_CREATE_SUCCESS = "CATEGORY_SUB_CREATE_SUCCESS";
export const CATEGORY_SUB_CREATE_FAIL = "CATEGORY_SUB_CREATE_FAIL";
export const CATEGORY_SUB_CREATE_RESET = "CATEGORY_SUB_CREATE_RESET";

export const CATEGORY_SUB_LIST_REQUEST = "CATEGORY_SUB_LIST_REQUEST";
export const CATEGORY_SUB_LIST_SUCCESS = "CATEGORY_SUB_LIST_SUCCESS";
export const CATEGORY_SUB_LIST_FAIL = "CATEGORY_SUB_LIST_FAIL";


export const CATEGORY_CHILD_CREATE_REQUEST = "CATEGORY_CHILD_CREATE_REQUEST";
export const CATEGORY_CHILD_CREATE_SUCCESS = "CATEGORY_CHILD_CREATE_SUCCESS";
export const CATEGORY_CHILD_CREATE_FAIL = "CATEGORY_CHILD_CREATE_FAIL";
export const CATEGORY_CHILD_CREATE_RESET = "CATEGORY_CHILD_CREATE_RESET";

export const CATEGORY_CHILD_LIST_REQUEST = "CATEGORY_CHILD_LIST_REQUEST";
export const CATEGORY_CHILD_LIST_SUCCESS = "CATEGORY_CHILD_LIST_SUCCESS";
export const CATEGORY_CHILD_LIST_FAIL = "CATEGORY_CHILD_LIST_FAIL";


