export const CATEGORY_MASTER_CREATE_REQUEST = "CATEGORY_MASTER_CREATE_REQUEST";
export const CATEGORY_MASTER_CREATE_SUCCESS = "CATEGORY_MASTER_CREATE_SUCCESS";
export const CATEGORY_MASTER_CREATE_FAIL = "CATEGORY_MASTER_CREATE_FAIL";
export const CATEGORY_MASTER_CREATE_RESET = "CATEGORY_MASTER_CREATE_RESET";

export const CATEGORY_MASTER_ALLLIST_REQUEST =
  "CATEGORY_MASTER_ALLLIST_REQUEST";
export const CATEGORY_MASTER_ALLLIST_SUCCESS =
  "CATEGORY_MASTER_ALLLIST_SUCCESS";
export const CATEGORY_MASTER_ALLLIST_FAIL = "CATEGORY_MASTER_ALLLIST_FAIL";
export const CATEGORY_MASTER_ALLLIST_RESET = " CATEGORY_MASTER_ALLLIST_RESET";
export const CATEGORY_MASTER_DEL_REQUEST = "CATEGORY_MASTER_DEL_REQUEST";
export const CATEGORY_MASTER_DEL_SUCCESS = "CATEGORY_MASTER_DEL_SUCCESS";
export const CATEGORY_MASTER_DEL_FAIL = "CATEGORY_MASTER_DEL_FAIL";
export const CATEGORY_MASTER_DEL_RESET = "CATEGORY_MASTER_DEL_RESET";

export const CATEGORY_MASTER_UPDATES_REQUEST =
  "CATEGORY_MASTER_UPDATES_REQUEST";
export const CATEGORY_MASTER_UPDATES_SUCCESS =
  "CATEGORY_MASTER_UPDATES_SUCCESS";
export const CATEGORY_MASTER_UPDATES_FAIL = "CATEGORY_MASTER_UPDATES_FAIL";
export const CATEGORY_MASTER_UPDATES_RESET = "CATEGORY_MASTER_UPDATES_RESET";

export const CATEGORY_CHILD_ALLLIST_REQUEST = "CATEGORY_CHILD_ALLLIST_REQUEST";
export const CATEGORY_CHILD_ALLLIST_SUCCESS = "CATEGORY_CHILD_ALLLIST_SUCCESS";
export const CATEGORY_CHILD_ALLLIST_FAIL = "CATEGORY_CHILD_ALLLIST_FAIL";

export const CATEGORY_CHILD_NEW_REQUEST = "CATEGORY_CHILD_NEW_REQUEST";
export const CATEGORY_CHILD_NEW_SUCCESS = "CATEGORY_CHILD_NEW_SUCCESS";
export const CATEGORY_CHILD_NEW_FAIL = "CATEGORY_CHILD_NEW_FAIL";

export const CATEGORY_GRAND_CHILD_NEW_REQUEST =
  "CATEGORY_GRAND_CHILD_NEW_REQUEST";
export const CATEGORY_GRAND_CHILD_NEW_SUCCESS =
  "CATEGORY_GRAND_CHILD_NEW_SUCCESS";
export const CATEGORY_GRAND_CHILD_NEW_FAIL = "CATEGORY_GRAND_CHILD_NEW_FAIL";

export const CATEGORY_GRAND_CHILD_ALLLIST_REQUEST =
  "CATEGORY_GRAND_CHILD_ALLLIST_REQUEST";
export const CATEGORY_GRAND_CHILD_ALLLIST_SUCCESS =
  "CATEGORY_GRAND_CHILD_ALLLIST_SUCCESS";
export const CATEGORY_GRAND_CHILD_ALLLIST_FAIL =
  "CATEGORY_GRAND_CHILD_ALLLIST_FAIL";

export const CATEGORY_UPDATES_REQUEST = "CATEGORY_UPDATES_REQUEST";
export const CATEGORY_UPDATES_SUCCESS = "CATEGORY_UPDATES_SUCCESS";
export const CATEGORY_UPDATES_FAIL = "CATEGORY_UPDATES_FAIL";
export const CATEGORY_UPDATES_RESET = "CATEGORY_UPDATES_RESET";

export const CATEGORY_CHILD_UPDATES_REQUEST = "CATEGORY_CHILD_UPDATES_REQUEST";
export const CATEGORY_CHILD_UPDATES_SUCCESS = "CATEGORY_CHILD_UPDATES_SUCCESS";
export const CATEGORY_CHILD_UPDATES_FAIL = "CATEGORY_CHILD_UPDATES_FAIL";
export const CATEGORY_CHILD_UPDATES_RESET = "CATEGORY_CHILD_UPDATES_RESET";

export const CATEGORY_GRAND_CHILD_UPDATES_REQUEST =
  "CATEGORY_GRAND_CHILD_UPDATES_REQUEST";
export const CATEGORY_GRAND_CHILD_UPDATES_SUCCESS =
  "CATEGORY_GRAND_CHILD_UPDATES_SUCCESS";
export const CATEGORY_GRAND_CHILD_UPDATES_FAIL =
  "CATEGORY_GRAND_CHILD_UPDATES_FAIL";
export const CATEGORY_GRAND_CHILD_UPDATES_RESET =
  "CATEGORY_GRAND_CHILD_UPDATES_RESET";

export const PARENT_ENABLE_UPDATE_REQUEST = "PARENT_ENABLE_UPDATE_REQUEST";
export const PARENT_ENABLE_UPDATE_SUCCESS = "PARENT_ENABLE_UPDATE_SUCCESS";
export const PARENT_ENABLE_UPDATE_FAIL = "PARENT_ENABLEUPDATE_FAIL";
export const PARENT_ENABLE_UPDATE_RESET = "PARENT_ENABLE_UPDATE_RESET";

export const CHILD_ENABLE_UPDATE_REQUEST = "CHILD_ENABLE_UPDATE_REQUEST";
export const CHILD_ENABLE_UPDATE_SUCCESS = "CHILD_ENABLE_UPDATE_SUCCESS";
export const CHILD_ENABLE_UPDATE_FAIL = "CHILD_ENABLEUPDATE_FAIL";
export const CHILD_ENABLE_UPDATE_RESET = "CHILD_ENABLE_UPDATE_RESET";

export const GRAND_CHILD_ENABLE_UPDATE_REQUEST =
  "GRAND_CHILD_ENABLE_UPDATE_REQUEST";
export const GRAND_CHILD_ENABLE_UPDATE_SUCCESS =
  "GRAND_CHILD_ENABLE_UPDATE_SUCCESS";
export const GRAND_CHILD_ENABLE_UPDATE_FAIL = "GRAND_CHILD_ENABLEUPDATE_FAIL";
export const GRAND_CHILD_ENABLE_UPDATE_RESET =
  "GRAND_CHILD_ENABLE_UPDATE_RESET";

export const PARENT_MULTIPLE_DELETE_REQUEST =
  "EMPLOYEE_MULTIPLE_DELETE_REQUEST";
export const PARENT_MULTIPLE_DELETE_SUCCESS =
  "EMPLOYEE_MULTIPLE_DELETE_SUCCESS";
export const PARENT_MULTIPLE_DELETE_FAIL = "EMPLOYEE_MULTIPLE_DELETE_FAIL";
export const PARENT_MULTIPLE_DELETE_RESET = "EMPLOYEE_MULTIPLE_DELETE_RESET";

export const CHILD_MULTIPLE_DELETE_REQUEST = "CHILD_MULTIPLE_DELETE_REQUEST";
export const CHILD_MULTIPLE_DELETE_SUCCESS = "CHILD_MULTIPLE_DELETE_SUCCESS";
export const CHILD_MULTIPLE_DELETE_FAIL = "CHILD_MULTIPLE_DELETE_FAIL";
export const CHILD_MULTIPLE_DELETE_RESET = "CHILD_MULTIPLE_DELETE_RESET";

export const GRAND_CHILD_MULTIPLE_DELETE_REQUEST =
  "GRAND_CHILD_MULTIPLE_DELETE_REQUEST";
export const GRAND_CHILD_MULTIPLE_DELETE_SUCCESS =
  "GRAND_CHILD_MULTIPLE_DELETE_SUCCESS";
export const GRAND_CHILD_MULTIPLE_DELETE_FAIL =
  "GRAND_CHILD_MULTIPLE_DELETE_FAIL";
export const GRAND_CHILD_MULTIPLE_DELETE_RESET =
  "GRAND_CHILD_MULTIPLE_DELETE_RESET";

export const CATEGORY_CHILD_UPDATE_REQUEST = "CATEGORY_CHILD_UPDATE_REQUEST";
export const CATEGORY_CHILD_UPDATE_SUCCESS = "CATEGORY_CHILD_UPDATE_SUCCESS";
export const CATEGORY_CHILD_UPDATE_FAIL = "CATEGORY_CHILD_UPDATE_FAIL";
export const CATEGORY_CHILD_UPDATE_RESET = "CATEGORY_CHILD_UPDATE_RESET";

export const CATEGORY_GRAND_CHILD_UPDATE_REQUEST =
  "CATEGORY_GRAND_CHILD_UPDATE_REQUEST";
export const CATEGORY_GRAND_CHILD_UPDATE_SUCCESS =
  "CATEGORY_GRAND_CHILD_UPDATE_SUCCESS";
export const CATEGORY_GRAND_CHILD_UPDATE_FAIL =
  "CATEGORY_GRAND_CHILD_UPDATE_FAIL";
export const CATEGORY_GRAND_CHILD_UPDATE_RESET =
  "CATEGORY_GRAND_CHILD_UPDATE_RESET";

  export const  CATEGORY_DELETE_REQUEST = 'CATEGORY_DELETE_REQUEST';
  export const  CATEGORY_DELETE_SUCCESS = 'CATEGORY_DELETE_REQUEST';
  export const  CATEGORY_DELETE_FAIL = 'CATEGORY_DELETE_REQUEST';
