export const CITY_SAVE_REQUEST = " CITY_SAVE_REQUEST";
export const CITY_SAVE_SUCCESS = " CITY_SAVE_SUCCESS";
export const CITY_SAVE_FAIL = " CITY_SAVE_FAIL";
export const CITY_SAVE_RESET = " CITY_SAVE_RESET";

export const CITY_LIST_REQUEST = " CITY_LIST_REQUEST";
export const CITY_LIST_SUCCESS = " CITY_LIST_SUCCESS";
export const CITY_LIST_FAIL = " CITY_LIST_FAIL";
export const CITY_LIST_RESET = " CITY_LIST_RESET";

export const CITY_UPDATE_REQUEST = " CITY_UPDATE_REQUEST";
export const CITY_UPDATE_SUCCESS = " CITY_UPDATE_SUCCESS";
export const CITY_UPDATE_FAIL = " CITY_UPDATE_FAIL";
export const CITY_UPDATE_RESET = " CITY_UPDATE_RESET";

export const CITY_DELETE_REQUEST = " CITY_DELETE_REQUEST";
export const CITY_DELETE_SUCCESS = " CITY_DELETE_SUCCESS";
export const CITY_DELETE_FAIL = " CITY_DELETE_FAIL";
export const CITY_DELETE_RESET = " CITY_DELETE_RESET";

export const CITY_ENABLE_REQUEST = " CITY_ENABLE_REQUEST";
export const CITY_ENABLE_SUCCESS = " CITY_ENABLE_SUCCESS";
export const CITY_ENABLE_FAIL = " CITY_ENABLE_FAIL";
export const CITY_ENABLE_RESET = " CITY_ENABLE_RESET";

export const CITY_CHECKBOX_REQUEST = " CITY_CHECKBOX_REQUEST";
export const CITY_CHECKBOX_SUCCESS = " CITY_CHECKBOX_SUCCESS";
export const CITY_CHECKBOX_FAIL = " CITY_CHECKBOX_FAIL";
export const CITY_CHECKBOX_RESET = " CITY_CHECKBOX_RESET";

export const CITY_BULKDELETE_REQUEST = " CITY_BULKDELETE_REQUEST";
export const CITY_BULKDELETE_SUCCESS = " CITY_BULKDELETE_SUCCESS";
export const CITY_BULKDELETE_FAIL = " CITY_BULKDELETE_FAIL";
export const CITY_BULKDELETE_RESET = " CITY_BULKDELETE_RESET";

export const CITY_ZONEASSIGHN_REQUEST = " CITY_ZONEASSIGHN_REQUEST";
export const CITY_ZONEASSIGHN_SUCCESS = " CITY_ZONEASSIGHN_SUCCESS";
export const CITY_ZONEASSIGHN_FAIL = " CITY_ZONEASSIGHN_FAIL";
export const CITY_ZONEASSIGHN_RESET = " CITY_ZONEASSIGHN_RESET";

export const CITY_ZONESAVE_REQUEST = " CITY_ZONESAVE_REQUEST";
export const CITY_ZONESAVE_SUCCESS = " CITY_ZONESAVE_SUCCESS";
export const CITY_ZONESAVE_FAIL = " CITY_ZONESAVE_FAIL";
export const CITY_ZONESAVE_RESET = " CITY_ZONESAVE_RESET";
