export const COMBO_SAVE_REQUEST = 'COMBO_SAVE_REQUEST';
export const COMBO_SAVE_SUCCESS = 'COMBO_SAVE_SUCCESS';
export const COMBO_SAVE_FAIL = 'COMBO_SAVE_FAIL';
export const COMBO_SAVE_RESET = 'COMBO_SAVE_RESET';

export const COMBO_UPDATE_REQUEST = 'COMBO_UPDATE_REQUEST';
export const COMBO_UPDATE_SUCCESS = 'COMBO_UPDATE_REQUEST';
export const COMBO_UPDATE_FAIL = 'COMBO_UPDATE_REQUEST';
export const COMBO_UPDATE_RESET = 'COMBO_UPDATE_REQUEST';

export const COMBO_DELETE_REQUEST = 'COMBO_DELETE_REQUEST';
export const COMBO_DELETE_SUCCESS = 'COMBO_DELETE_SUCCESS';
export const COMBO_DELETE_FAIL = 'COMBO_DELETE_FAIL';
export const COMBO_DELETE_RESET = 'COMBO_DELETE_RESET';

export const COMBO_DETAILS_REQUEST = 'COMBO_DETAILS_REQUEST';
export const COMBO_DETAILS_SUCCESS = 'COMBO_DETAILS_SUCCESS';
export const COMBO_DETAILS_FAIL = 'COMBO_DETAILS_FAIL';
export const COMBO_DETAILS_RESET = 'COMBO_DETAILS_RESET';
