export const COUNTRY_DETAIL_SAVE_REQUEST = "COUNTRY_DETAIL_SAVE_REQUEST";
export const COUNTRY_DETAIL_SAVE_SUCCESS = "COUNTRY_DETAIL_SAVE_SUCCESS";
export const COUNTRY_DETAIL_SAVE_FAIL = "COUNTRY_DETAIL_SAVE_FAIL";
export const COUNTRY_DETAIL_SAVE_RESET = "COUNTRY_DETAIL_SAVE_RESET";

export const COUNTRY_DETAIL_LIST_REQUEST = "COUNTRY_DETAIL_LIST_REQUEST";
export const COUNTRY_DETAIL_LIST_SUCCESS = "COUNTRY_DETAIL_LIST_SUCCESS";
export const COUNTRY_DETAIL_LIST_FAIL = "COUNTRY_DETAIL_LIST_FAIL";
export const COUNTRY_DETAIL_LIST_RESET = "COUNTRY_DETAIL_LIST_RESET";

export const COUNTRY_DETAIL_UPDATE_REQUEST = "COUNTRY_DETAIL_UPDATE_REQUEST";
export const COUNTRY_DETAIL_UPDATE_SUCCESS = "COUNTRY_DETAIL_UPDATE_SUCCESS";
export const COUNTRY_DETAIL_UPDATE_FAIL = "COUNTRY_DETAIL_UPDATE_FAIL";
export const COUNTRY_DETAIL_UPDATE_RESET = "COUNTRY_DETAIL_UPDATE_RESET";

export const COUNTRY_DETAIL_DELETE_REQUEST = "COUNTRY_DETAIL_DELETE_REQUEST";
export const COUNTRY_DETAIL_DELETE_SUCCESS = "COUNTRY_DETAIL_DELETE_SUCCESS";
export const COUNTRY_DETAIL_DELETE_FAIL = "COUNTRY_DETAIL_DELETE_FAIL";
export const COUNTRY_DETAIL_DELETE_RESET = "COUNTRY_DETAIL_DELETE_RESET";

export const COUNTRY_ENABLE_REQUEST = "COUNTRY_ENABLE_REQUEST";
export const COUNTRY_ENABLE_SUCCESS = "COUNTRY_ENABLE_SUCCESS";
export const COUNTRY_ENABLE_FAIL = "COUNTRY_ENABLE_FAIL";
export const COUNTRY_ENABLE_RESET = "COUNTRY_ENABLE_RESET";

export const COUNTRY_ENABLE_UPDATES_REQUEST = "COUNTRY_ENABLE_UPDATES_REQUEST";
export const COUNTRY_ENABLE_UPDATES_SUCCESS = "COUNTRY_ENABLE_UPDATES_SUCCESS";
export const COUNTRY_ENABLE_UPDATES_FAIL = "COUNTRY_ENABLE_UPDATES_FAIL";
export const COUNTRY_ENABLE_UPDATES_RESET = "COUNTRY_ENABLE_UPDATES_RESET";

export const COUNTRY_MULTIPLE_DELETE_REQUEST = "COUNTRY_MULTIPLE_DELETE_REQUEST";
export const COUNTRY_MULTIPLE_DELETE_SUCCESS = "COUNTRY_MULTIPLE_DELETE_SUCCESS";
export const COUNTRY_MULTIPLE_DELETE_FAIL = "COUNTRY_MULTIPLE_DELETE_FAIL";
export const COUNTRY_MULTIPLE_DELETE_RESET = "COUNTRY_MULTIPLE_DELETE_RESET";