export const CUSTOMER_ADDRESS_REQUEST = 'CUSTOMER_ADDRESS_REQUEST';
export const CUSTOMER_ADDRESS_SUCCESS = 'CUSTOMER_ADDRESS_SUCCESS';
export const CUSTOMER_ADDRESS_FAIL = 'CUSTOMER_ADDRESS_FAIL';
export const CUSTOMER_ADDRESS_RESET = 'CUSTOMER_ADDRESS_RESET';

export const CUSTOMER_ADDRESS_LIST_REQUEST = 'CUSTOMER_ADDRESS_LIST_REQUEST';
export const CUSTOMER_ADDRESS_LIST_SUCCESS = 'CUSTOMER_ADDRESS_LIST_SUCCESS';
export const CUSTOMER_ADDRESS_LIST_FAIL = 'CUSTOMER_ADDRESS_LIST_FAIL';
export const CUSTOMER_ADDRESS_LIST_RESET = 'CUSTOMER_ADDRESS_LIST_RESET';

export const CUSTOMER_ADDRESS_UPDATE_REQUEST = 'CUSTOMER_ADDRESS_UPDATE_REQUEST';
export const CUSTOMER_ADDRESS_UPDATE_SUCCESS = 'CUSTOMER_ADDRESS_UPDATE_SUCCESS';
export const CUSTOMER_ADDRESS_UPDATE_FAIL = 'CUSTOMER_ADDRESS_UPDATE_FAIL';
export const CUSTOMER_ADDRESS_UPDATE_RESET = 'CUSTOMER_ADDRESS_UPDATE_RESET';

export const CUSTOMER_ADDRESS_DELETE_REQUEST = 'CUSTOMER_ADDRESS_DELETE_REQUEST';
export const CUSTOMER_ADDRESS_DELETE_SUCCESS = 'CUSTOMER_ADDRESS_DELETE_SUCCESS';
export const CUSTOMER_ADDRESS_DELETE_FAIL = 'CUSTOMER_ADDRESS_DELETE_FAIL';
export const CUSTOMER_ADDRESS_DELETE_RESET = 'CUSTOMER_ADDRESS_DELETE_RESET';

export const CUSTOMER_PRODUCT_ACTIVE_UPDATE_REQUEST = ' CUSTOMER_PRODUCT_ACTIVE_UPDATE_REQUEST';
export const CUSTOMER_PRODUCT_ACTIVE_UPDATE_SUCCESS = ' CUSTOMER_PRODUCT_ACTIVE_UPDATE_SUCCESS';
export const CUSTOMER_PRODUCT_ACTIVE_UPDATE_FAIL = ' CUSTOMER_PRODUCT_ACTIVE_UPDATE_FAIL';
export const CUSTOMER_PRODUCT_ACTIVE_UPDATE_RESET = ' CUSTOMER_PRODUCT_ACTIVE_UPDATE_RESET';

export const CUSTOMER_ADDRESS_BULK_DELETE_REQUEST = ' CUSTOMER_ADDRESS_BULK_DELETE_REQUEST';
export const CUSTOMER_ADDRESS_BULK_DELETE_SUCCESS = ' CUSTOMER_ADDRESS_BULK_DELETE_SUCCESS';
export const CUSTOMER_ADDRESS_BULK_DELETE_FAIL = ' CUSTOMER_ADDRESS_BULK_DELETE_FAIL';
export const CUSTOMER_ADDRESS_BULK_DELETE_RESET = ' CUSTOMER_ADDRESS_BULK_DELETE_RESET';

export const CUSTOMER_ADDRESS_ENABLE_UPDATE_REQUEST = 'CUSTOMER_ADDRESS_ENABLE_UPDATE_REQUEST';
export const CUSTOMER_ADDRESS_ENABLE_UPDATE_SUCCESS = 'CUSTOMER_ADDRESS_ENABLE_UPDATE_SUCCESS';
export const CUSTOMER_ADDRESS_ENABLE_UPDATE_FAIL = 'CUSTOMER_ADDRESS_ENABLEUPDATE_FAIL';
export const CUSTOMER_ADDRESS_ENABLE_UPDATE_RESET = 'CUSTOMER_ADDRESS_ENABLE_UPDATE_RESET';