export const CUSTOMER_DETAILS_REQUEST = "CUSTOMER_DETAILS_REQUEST";
export const CUSTOMER_DETAILS_SUCCESS = "CUSTOMER_DETAILS_SUCCESS";
export const CUSTOMER_DETAILS_FAIL = "CUSTOMER_DETAILS_FAIL";
export const CUSTOMER_DETAILS_RESET = "CUSTOMER_DETAILS_RESET";

export const CUSTOMER_LIST_REQUEST = "CUSTOMER_LIST_REQUEST";
export const CUSTOMER_LIST_SUCCESS = "CUSTOMER_LIST_SUCCESS";
export const CUSTOMER_LIST_FAIL = "CUSTOMER_LIST_FAIL";

export const CUSTOMER_UPDATE_REQUEST = "CUSTOMER_UPDATE_REQUEST";
export const CUSTOMER_UPDATE_SUCCESS = "CUSTOMER_UPDATE_SUCCESS";
export const CUSTOMER_UPDATE_FAIL = "CUSTOMER_UPDATE_FAIL";
export const CUSTOMER_UPDATE_RESET = "CUSTOMER_UPDATE_RESET";

export const CUSTOMER_DELETE_REQUEST = "CUSTOMER_DELETE_REQUEST";
export const CUSTOMER_DELETE_SUCCESS = "CUSTOMER_DELETE_SUCCESS";
export const CUSTOMER_DELETE_FAIL = "CUSTOMER_DELETE_FAIL";
export const CUSTOMER_DELETE_RESET = "CUSTOMER_DELETE_RESET";

export const CUSTOMER_ENABLE_UPDATE_REQUEST = "CUSTOMER_ENABLE_UPDATE_REQUEST";
export const CUSTOMER_ENABLE_UPDATE_SUCCESS = "CUSTOMER_ENABLE_UPDATE_SUCCESS";
export const CUSTOMER_ENABLE_UPDATE_FAIL = "CUSTOMER_ENABLE_UPDATE_FAIL";
export const CUSTOMER_ENABLE_UPDATE_RESET = "CUSTOMER_ENABLE_UPDATE_RESET";

export const CUSTOMER_BULK_UPDATE_REQUEST = "CUSTOMER_BULK_UPDATE_REQUEST";
export const CUSTOMER_BULK_UPDATE_SUCCESS = "CUSTOMER_BULK_UPDATE_SUCCESS";
export const CUSTOMER_BULK_UPDATE_FAIL = "CUSTOMER_BULK_UPDATE_FAIL";
export const CUSTOMER_BULK_UPDATE_RESET = "CUSTOMER_BULK_UPDATE_RESET";

export const CUSTOMER_BULK_DELETE_REQUEST = "CUSTOMER_BULK_DELETE_REQUEST";
export const CUSTOMER_BULK_DELETE_SUCCESS = "CUSTOMER_BULK_DELETE_SUCCESS";
export const CUSTOMER_BULK_DELETE_FAIL = "CUSTOMER_BULK_DELETE_FAIL";
export const CUSTOMER_BULK_DELETE_RESET = "CUSTOMER_BULK_DELETE_RESET";
