export const EMPLOYEE_PROFLE_REQUEST = 'EMPLOYEE_PROFLE_REQUEST';
export const EMPLOYEE_PROFLE_SUCCESS = 'EMPLOYEE_PROFLE_SUCCESS';
export const EMPLOYEE_PROFLE_FAIL = 'EMPLOYEE_PROFLE_FAIL';
export const EMPLOYEE_PROFLE_RESET = 'EMPLOYEE_PROFLE_RESET';


export const EMPLOYEE_DETAIL_REQUEST = 'EMPLOYEE_DETAIL_REQUEST';
export const EMPLOYEE_DETAIL_SUCCESS = 'EMPLOYEE_DETAIL_SUCCESS';
export const EMPLOYEE_DETAIL_FAIL = 'EMPLOYEE_DETAIL_FAIL';
export const EMPLOYEE_DETAIL_RESET = 'EMPLOYEE_DETAIL_RESET';

export const EMPLOYEE_PROFLE_LIST_REQUEST = "EMPLOYEE_PROFLE_LIST_REQUEST";
export const EMPLOYEE_PROFLE_LIST_SUCCESS = "EMPLOYEE_PROFLE_LIST_SUCCESS";
export const EMPLOYEE_PROFLE_LIST_FAIL = "EMPLOYEE_PROFLE_LIST_FAIL";

export const EMPLOYEE_LIST_REQUEST = "EMPLOYEE_LIST_REQUEST";
export const EMPLOYEE_LIST_SUCCESS = "EMPLOYEE_LIST_SUCCESS";
export const EMPLOYEE_LIST_FAIL = "EMPLOYEE_LIST_FAIL";

export const EMPLOYEE_UPDATE_REQUEST = 'EMPLOYEE_UPDATE_REQUEST';
export const EMPLOYEE_UPDATE_SUCCESS = 'EMPLOYEE_UPDATE_SUCCESS';
export const EMPLOYEE_UPDATE_FAIL = 'EMPLOYEE_UPDATE_FAIL';
export const EMPLOYEE_UPDATE_RESET = 'EMPLOYEE_UPDATE_RESET';

export const EMPLOYEE_DELETE_REQUEST = 'EMPLOYEE_DELETE_REQUEST';
export const EMPLOYEE_DELETE_SUCCESS = 'EMPLOYEE_DELETE_SUCCESS';
export const EMPLOYEE_DELETE_FAIL = 'EMPLOYEE_DELETE_FAIL';
export const EMPLOYEE_DELETE_RESET = 'EMPLOYEE_DELETE_RESET';


export const EMPLOYEE_MULTIPLE_DELETE_REQUEST = 'EMPLOYEE_MULTIPLE_DELETE_REQUEST';
export const EMPLOYEE_MULTIPLE_DELETE_SUCCESS = 'EMPLOYEE_MULTIPLE_DELETE_SUCCESS';
export const EMPLOYEE_MULTIPLE_DELETE_FAIL = 'EMPLOYEE_MULTIPLE_DELETE_FAIL';
export const EMPLOYEE_MULTIPLE_DELETE_RESET = 'EMPLOYEE_MULTIPLE_DELETE_RESET';

export const EMPLOYEE_PROFLE_UPDATE_REQUEST = 'EMPLOYEE_PROFLE_UPDATE_REQUEST';
export const EMPLOYEE_PROFLE_UPDATE_SUCCESS = 'EMPLOYEE_PROFLE_UPDATE_SUCCESS';
export const EMPLOYEE_PROFLE_UPDATE_FAIL = 'EMPLOYEE_PROFLE_UPDATE_FAIL';
export const EMPLOYEE_PROFLE_UPDATE_RESET = 'EMPLOYEE_PROFLE_UPDATE_RESET';

export const EMPLOYEE_PROFLE_DELETE_REQUEST = 'EMPLOYEE_PROFLE_DELETE_REQUEST';
export const EMPLOYEE_PROFLE_DELETE_SUCCESS = 'EMPLOYEE_PROFLE_DELETE_SUCCESS';
export const EMPLOYEE_PROFLE_DELETE_FAIL = 'EMPLOYEE_PROFLE_DELETE_FAIL';
export const EMPLOYEE_PROFLE_DELETE_RESET = 'EMPLOYEE_PROFLE_DELETE_RESET';


export const EMPLOYEE_ACTIVE_UPDATE_REQUEST = 'EMPLOYEE_ACTIVE_UPDATE_REQUEST';
export const EMPLOYEE_ACTIVE_UPDATE_SUCCESS = 'EMPLOYEE_ACTIVE_UPDATE_SUCCESS';
export const EMPLOYEE_ACTIVE_UPDATE_FAIL = 'EMPLOYEE_ACTIVE_UPDATE_FAIL';
export const EMPLOYEE_ACTIVE_UPDATE_RESET = 'EMPLOYEE_ACTIVE_UPDATE_RESET';


export const EMPLOYEE_ENABLE_UPDATE_REQUEST = 'EMPLOYEE_ENABLE_UPDATE_REQUEST';
export const EMPLOYEE_ENABLE_UPDATE_SUCCESS = 'EMPLOYEE_ENABLE_UPDATE_SUCCESS';
export const EMPLOYEE_ENABLE_UPDATE_FAIL = 'EMPLOYEE_ENABLEUPDATE_FAIL';
export const EMPLOYEE_ENABLE_UPDATE_RESET = 'EMPLOYEE_ENABLE_UPDATE_RESET';

