export const GENERAL_DETAIL_REQUEST = "GENERAL_DETAIL_REQUEST";
export const GENERAL_DETAIL_SUCCESS = "GENERAL_DETAIL_SUCCESS";
export const GENERAL_DETAIL_FAIL = "GENERAL_DETAIL_FAIL";
export const GENERAL_DETAIL_RESET = "GENERAL_DETAIL_RESET";

export const GENERAL_DETAIL_LIST_REQUEST = "GENERAL_DETAIL_LIST_REQUEST";
export const GENERAL_DETAIL_LIST_SUCCESS = "GENERAL_DETAIL_LIST_SUCCESS";
export const GENERAL_DETAIL_LIST_FAIL = "GENERAL_DETAIL_LIST_FAIL";
export const GENERAL_DETAIL_LIST_RESET = "GENERAL_DETAIL_LIST_RESET";

export const GENERAL_DETAIL_UPDATE_REQUEST = "GENERAL_DETAIL_UPDATE_REQUEST";
export const GENERAL_DETAIL_UPDATE_SUCCESS = "GENERAL_DETAIL_UPDATE_SUCCESS";
export const GENERAL_DETAIL_UPDATE_FAIL = "GENERAL_DETAIL_UPDATE_FAIL";
export const GENERAL_DETAIL_UPDATE_RESET = "GENERAL_DETAIL_UPDATE_RESET";

export const GENERAL_DETAIL_ALLLIST_REQUEST = "GENERAL_DETAIL_ALLLIST_REQUEST";
export const GENERAL_DETAIL_ALLLIST_SUCCESS = "GENERAL_DETAIL_ALLLIST_SUCCESS";
export const GENERAL_DETAIL_ALLLIST_FAIL = "GENERAL_DETAIL_ALLLIST_FAIL";
export const GENERAL_DETAIL_ALLLIST_RESET = "GENERAL_DETAIL_ALLLIST_RESET";

export const GENERAL_DETAIL_DELETE_REQUEST = "GENERAL_DETAIL_DELETE_REQUEST";
export const GENERAL_DETAIL_DELETE_SUCCESS = "GENERAL_DETAIL_DELETE_SUCCESS";
export const GENERAL_DETAIL_DELETE_FAIL = "GENERAL_DETAIL_DELETE_FAIL";
export const GENERAL_DETAIL_DELETE_RESET = "GENERAL_DETAIL_DELETE_RESET";

export const GENERAL_DETAIL_ACTIVATE_REQUEST = "GENERAL_DETAIL_ACTIVATE_REQUEST";
export const GENERAL_DETAIL_ACTIVATE_SUCCESS = "GENERAL_DETAIL_ACTIVATE_SUCCESS";
export const GENERAL_DETAIL_ACTIVATE_FAIL = "GENERAL_DETAIL_ACTIVATE_FAIL";
export const GENERAL_DETAIL_ACTIVATE_RESET = "GENERAL_DETAIL_ACTIVATE_RESET";

export const GENERAL_DETAIL_ENABLE_REQUEST = "GENERAL_DETAIL_ENABLE_REQUEST";
export const GENERAL_DETAIL_ENABLE_SUCCESS = "GENERAL_DETAIL_ENABLE_SUCCESS";
export const GENERAL_DETAIL_ENABLE_FAIL = "GENERAL_DETAIL_ENABLE_FAIL";
export const GENERAL_DETAIL_ENABLE_RESET = "GENERAL_DETAIL_ENABLE_RESET";

export const GENERAL_MULTIPLE_DELETE_REQUEST = "GENERAL_MULTIPLE_DELETE_REQUEST";
export const GENERAL_MULTIPLE_DELETE_SUCCESS = "GENERAL_MULTIPLE_DELETE_SUCCESS";
export const GENERAL_MULTIPLE_DELETE_FAIL = "GENERAL_MULTIPLE_DELETE_FAIL";
export const GENERAL_MULTIPLE_DELETE_RESET = "GENERAL_MULTIPLE_DELETE_RESET";

export const GENERAL_ENABLE_REQUEST = "GENERAL_ENABLE_REQUEST";
export const GENERAL_ENABLE_SUCCESS = "GENERAL_ENABLE_SUCCESS";
export const GENERAL_ENABLE_FAIL = "GENERAL_ENABLE_FAIL";
export const GENERAL_ENABLE_RESET = "GENERAL_ENABLE_RESET";