export const OPTIONS_SAVE_REQUEST = "OPTIONS_SAVE_REQUEST";
export const OPTIONS_SAVE_SUCCESS = "OPTIONS_SAVE_SUCCESS";
export const OPTIONS_SAVE_FAIL = "OPTIONS_SAVE_FAIL";
export const OPTIONS_SAVE_RESET = "OPTIONS_SAVE_RESET";

export const OPTIONS_DETAILS_LIST_REQUEST = "OPTIONS_DETAILS_LIST_REQUEST";
export const OPTIONS_DETAILS_LIST_SUCCESS = "OPTIONS_DETAILS_LIST_SUCCESS";
export const OPTIONS_DETAILS_LIST_FAIL = "OPTIONS_DETAILS_LIST_FAIL";
export const OPTIONS_DETAILS_LIST_RESET = "OPTIONS_DETAILS_LIST_RESET";

export const OPTIONS_DETAILS_UPDATE_REQUEST = "OPTIONS_DETAILS_UPDATE_REQUEST";
export const OPTIONS_DETAILS_UPDATE_SUCCESS = "OPTIONS_DETAILS_UPDATE_SUCCESS";
export const OPTIONS_DETAILS_UPDATE_FAIL = "OPTIONS_DETAILS_UPDATE_FAIL";
export const OPTIONS_DETAILS_UPDATE_RESET = "OPTIONS_DETAILS_UPDATE_RESET";