export const PAY_SAVE_REQUEST = " PAY_SAVE_REQUEST";
export const PAY_SAVE_SUCCESS = " PAY_SAVE_SUCCESS";
export const PAY_SAVE_FAIL = " PAY_SAVE_FAIL";
export const PAY_SAVE_RESET = " PAY_SAVE_RESET";

export const PAY_LIST_REQUEST = " PAY_LIST_REQUEST";
export const PAY_LIST_SUCCESS = " PAY_LIST_SUCCESS";
export const PAY_LIST_FAIL = " PAY_LIST_FAIL";
export const PAY_LIST_RESET = " PAY_LIST_RESET";

export const PAY_UPDATE_REQUEST = " PAY_UPDATE_REQUEST";
export const PAY_UPDATE_SUCCESS = " PAY_UPDATE_SUCCESS";
export const PAY_UPDATE_FAIL = " PAY_UPDATE_FAIL";
export const PAY_UPDATE_RESET = " PAY_UPDATE_RESET";

export const PAY_DELETE_REQUEST = " PAY_DELETE_REQUEST";
export const PAY_DELETE_SUCCESS = " PAY_DELETE_SUCCESS";
export const PAY_DELETE_FAIL = " PAY_DELETE_FAIL";
export const PAY_DELETE_RESET = " PAY_DELETE_RESET";

export const PAY_ENABLE_REQUEST = " PAY_ENABLE_REQUEST";
export const PAY_ENABLE_SUCCESS = " PAY_ENABLE_SUCCESS";
export const PAY_ENABLE_FAIL = " PAY_ENABLE_FAIL";
export const PAY_ENABLE_RESET = " PAY_ENABLE_RESET";

export const PAY_CHECKBOX_REQUEST = " PAY_CHECKBOX_REQUEST";
export const PAY_CHECKBOX_SUCCESS = " PAY_CHECKBOX_SUCCESS";
export const PAY_CHECKBOX_FAIL = " PAY_CHECKBOX_FAIL";
export const PAY_CHECKBOX_RESET = " PAY_CHECKBOX_RESET";

export const PAY_BULKDELETE_REQUEST = " PAY_BULKDELETE_REQUEST";
export const PAY_BULKDELETE_SUCCESS = " PAY_BULKDELETE_SUCCESS";
export const PAY_BULKDELETE_FAIL = " PAY_BULKDELETE_FAIL";
export const PAY_BULKDELETE_RESET = " PAY_BULKDELETE_RESET";
