export const PRODUCT_SHIPPING_DETAILS_REQUEST = 'PRODUCT_SHIPPING_DETAILS_REQUEST';
export const PRODUCT_SHIPPING_DETAILS_SUCCESS = 'PRODUCT_SHIPPING_DETAILS_SUCCESS';
export const PRODUCT_SHIPPING_DETAILS_FAIL = 'PRODUCT_SHIPPING_DETAILS_FAIL';
export const PRODUCT_SHIPPING_DETAILS_RESET = 'PRODUCT_SHIPPING_DETAILS_RESET';


export const PRODUCT_SHIPPING_UPDATE_REQUEST = 'PRODUCT_SHIPPING_UPDATE_REQUEST';
export const PRODUCT_SHIPPING_UPDATE_SUCCESS = 'PRODUCT_SHIPPING_UPDATE_SUCCESS';
export const PRODUCT_SHIPPING_UPDATE_FAIL = 'PRODUCT_SHIPPING_UPDATE_FAIL';
export const PRODUCT_SHIPPING_UPDATE_RESET = 'PRODUCT_SHIPPING_UPDATE_RESET';

export const PRODUCT_SHIPPING_LIST_REQUEST = 'PRODUCT_SHIPPING_LIST_REQUEST';
export const PRODUCT_SHIPPING_LIST_SUCCESS = 'PRODUCT_SHIPPING_LIST_SUCCESS';
export const PRODUCT_SHIPPING_LIST_FAIL = 'PRODUCT_SHIPPING_LIST_FAIL';
export const PRODUCT_SHIPPING_LIST_RESET = 'PRODUCT_SHIPPING_LIST_RESET';