export const PRODUCT_QUANTITIES_REQUEST = 'PRODUCT_QUANTITIES_REQUEST';
export const PRODUCT_QUANTITIES_SUCCESS = 'PRODUCT_QUANTITIES_SUCCESS';
export const PRODUCT_QUANTITIES_FAIL = 'PRODUCT_QUANTITIES__FAIL';
export const PRODUCT_QUANTITIES_RESET = 'PRODUCT_QUANTITIES_RESET';

export const PRODUCT_QUANTITIES_UPDATE_REQUEST = 'PRODUCT_QUANTITIES_UPDATE_REQUEST';
export const PRODUCT_QUANTITIES_UPDATE_SUCCESS = 'PRODUCT_QUANTITIES_UPDATE_SUCCESS';
export const PRODUCT_QUANTITIES_UPDATE_FAIL = 'PRODUCT_QUANTITIES_UPDATE_FAIL';
export const PRODUCT_QUANTITIES_UPDATE_RESET = 'PRODUCT_QUANTITIES_UPDATE_RESET';

export const PRODUCT_QUANTITIES_LIST_REQUEST = 'PRODUCT_QUANTITIES_LIST_REQUEST';
export const PRODUCT_QUANTITIES_LIST_SUCCESS = 'PRODUCT_QUANTITIES_LIST_SUCCESS';
export const PRODUCT_QUANTITIES_LIST_FAIL = 'PRODUCT_QUANTITIES_LIST_FAIL';
export const PRODUCT_QUANTITIES_LIST_RESET = 'PRODUCT_QUANTITIES_LIST_RESET';