export const PPRODUCT_ENQUIRY_LIST_REQUEST = 'PPRODUCT_ENQUIRY_LIST_REQUEST';
export const PPRODUCT_ENQUIRY_LIST_SUCCESS = 'PPRODUCT_ENQUIRY_LIST_SUCCESS';
export const PPRODUCT_ENQUIRY_LIST_FAIL = 'PPRODUCT_ENQUIRY_LIST_FAIL';
export const PPRODUCT_ENQUIRY_LIST_RESET = 'PPRODUCT_ENQUIRY_LIST_RESET';