export const PRICING_DETAILS_REQUEST = 'PRICING_DETAILS_REQUEST';
export const PRICING_DETAILS_SUCCESS = 'PRICING_DETAILS_SUCCESS';
export const PRICING_DETAILS_FAIL = 'PRICING_DETAILS_FAIL';
export const PRICING_DETAILS_RESET = 'PRICING_DETAILS_RESET';

export const PRICING_DETAILS_LIST_REQUEST = 'PRICING_DETAILS_LIST_REQUEST';
export const PRICING_DETAILS_LIST_SUCCESS = 'PRICING_DETAILS_LIST_SUCCESS';
export const PRICING_DETAILS_LIST_FAIL = 'PRICING_DETAILS_LIST_FAIL';
export const PRICING_DETAILS_LIST_RESET = 'PRICING_DETAILS_LIST_RESET';

export const PRICING_DETAILS_LAST_LIST_REQUEST = 'PRICING_DETAILS_LAST_LIST_REQUEST';
export const PRICING_DETAILS_LAST_LIST_SUCCESS = 'PRICING_DETAILS_LAST_LIST_SUCCESS';
export const PRICING_DETAILS_LAST_LIST_FAIL = 'PRICING_DETAILS_LAST_LIST_FAIL';
export const PRICING_DETAILS_LAST_LIST_RESET = 'PRICING_DETAILS_LAST_LIST_RESET';

export const PRICING_DETAILS_UPDATE_REQUEST = 'PRICING_DETAILS_UPDATE_REQUEST';
export const PRICING_DETAILS_UPDATE_SUCCESS = 'PRICING_DETAILS_UPDATE_SUCCESS';
export const PRICING_DETAILS_UPDATE_FAIL = 'PRICING_DETAILS_UPDATE_FAIL';
export const PRICING_DETAILS_UPDATE_RESET = 'PRICING_DETAILS_UPDATE_RESET';