export const PPRODUCT_ENQUIRY_LIST_REQUEST = "PPRODUCT_ENQUIRY_LIST_REQUEST";
export const PPRODUCT_ENQUIRY_LIST_SUCCESS = "PPRODUCT_ENQUIRY_LIST_SUCCESS";
export const PPRODUCT_ENQUIRY_LIST_FAIL = "PPRODUCT_ENQUIRY_LIST_FAIL";
export const PPRODUCT_ENQUIRY_LIST_RESET = "PPRODUCT_ENQUIRY_LIST_RESET";

export const PRODUCT_ENQUIRY_DELETE_REQUEST = "PPRODUCT_ENQUIRY_DELETE_REQUEST";
export const PRODUCT_ENQUIRY_DELETE_SUCCESS = "PPRODUCT_ENQUIRY_DELETE_SUCCESS";
export const PRODUCT_ENQUIRY_DELETE_FAIL = "PPRODUCT_ENQUIRY_DELETE_FAIL";
export const PRODUCT_ENQUIRY_DELETE_RESET = "PPRODUCT_ENQUIRY_DELETE_RESET";

export const PRODUCT_NOTIFICATION_LIST_REQUEST =
    "PRODUCT_NOTIFICATION_LIST_REQUEST";
export const PRODUCT_NOTIFICATION_LIST_SUCCESS =
    "PRODUCT_NOTIFICATION_LIST_SUCCESS";
export const PRODUCT_NOTIFICATION_LIST_FAIL = "PRODUCT_NOTIFICATION_LIST_FAIL";
export const PRODUCT_NOTIFICATION_LIST_RESET =
    "PRODUCT_NOTIFICATION_LIST_RESET";

export const NOTIFICATION_DELETE_REQUEST = "NOTIFICATION_DELETE_REQUEST";
export const NOTIFICATION_DELETE_SUCCESS = "NOTIFICATION_DELETE_SUCCESS";
export const NOTIFICATION_DELETE_FAIL = "NOTIFICATION_DELETE_FAIL";
export const NOTIFICATION_DELETE_RESET = "NOTIFICATION_DELETE_RESET";

export const NOTIFICATION_CLEAR_REQUEST = "NOTIFICATION_CLEAR_REQUEST";
export const NOTIFICATION_CLEAR_SUCCESS = "NOTIFICATION_CLEAR_SUCCESS";
export const NOTIFICATION_CLEAR_FAIL = "NOTIFICATION_CLEAR_FAIL";
export const NOTIFICATION_CLEAR_RESET = "NOTIFICATION_CLEAR_RESET";


