export const SEO_SAVE_REQUEST = "SEO_SAVE_REQUEST";
export const SEO_SAVE_SUCCESS = "SEO_SAVE_SUCCESS";
export const SEO_SAVE_FAIL = "SEO_SAVE_FAIL";
export const SEO_SAVE_RESET = "SEO_SAVE_RESET";

export const SEO_DETAILS_LIST_REQUEST = "SEO_DETAILS_LIST_REQUEST";
export const SEO_DETAILS_LIST_SUCCESS = "SEO_DETAILS_LIST_SUCCESS";
export const SEO_DETAILS_LIST_FAIL = "SEO_DETAILS_LIST_FAIL";
export const SEO_DETAILS_LIST_RESET = "SEO_DETAILS_LIST_RESET";

export const SEO_DETAILS_UPDATE_REQUEST = "SEO_DETAILS_UPDATE_REQUEST";
export const SEO_DETAILS_UPDATE_SUCCESS = "SEO_DETAILS_UPDATE_SUCCESS";
export const SEO_DETAILS_UPDATE_FAIL = "SEO_DETAILS_UPDATE_FAIL";
export const SEO_DETAILS_UPDATE_RESET = "SEO_DETAILS_UPDATE_RESET";
