export const SHIPPING_SAVE_REQUEST = "SHIPPING_SAVE_REQUEST";
export const SHIPPING_SAVE_SUCCESS = "SHIPPING_SAVE_SUCCESS";
export const SHIPPING_SAVE_FAIL = "SHIPPING_SAVE_FAIL";
export const SHIPPING_SAVE_RESET = "SHIPPING_SAVE_RESET";

export const SHIPPING_LIST_REQUEST = "SHIPPING_LIST_REQUEST";
export const SHIPPING_LIST_SUCCESS = "SHIPPING_LIST_SUCCESS";
export const SHIPPING_LIST_FAIL = "SHIPPING_LIST_FAIL";
export const SHIPPING_LIST_RESET = "SHIPPING_LIST_RESET";

export const SHIPPING_ALLLIST_REQUEST = "SHIPPING_ALLLIST_REQUEST";
export const SHIPPING_ALLLIST_SUCCESS = "SHIPPING_ALLLIST_SUCCESS";
export const SHIPPING_ALLLIST_FAIL = "SHIPPING_ALLLIST_FAIL";
export const SHIPPING_ALLLIST_RESET = "SHIPPING_ALLLIST_RESET";

export const SHIPPING_UPDATE_REQUEST = "SHIPPING_UPDATE_REQUEST";
export const SHIPPING_UPDATE_SUCCESS = "SHIPPING_UPDATE_SUCCESS";
export const SHIPPING_UPDATE_FAIL = "SHIPPING_UPDATE_FAIL";
export const SHIPPING_UPDATE_RESET = "SHIPPING_UPDATE_RESET";

