export const SIZEWEIGHTGROUP_SAVE_REQUEST = "SIZEWEIGHTGROUP_SAVE_REQUEST";
export const SIZEWEIGHTGROUP_SAVE_SUCCESS = "SIZEWEIGHTGROUP_SAVE_SUCCESS";
export const SIZEWEIGHTGROUP_SAVE_FAIL = "SIZEWEIGHTGROUP_SAVE_FAIL";
export const SIZEWEIGHTGROUP_SAVE_RESET = "SIZEWEIGHTGROUP_SAVE_RESET";

export const SUMMARY_SAVE_REQUEST = " SUMMARY_SAVE_REQUEST";
export const SUMMARY_SAVE_SUCCESS = " SUMMARY_SAVE_SUCCESS";
export const SUMMARY_SAVE_FAIL = " SUMMARY_SAVE_FAIL";
export const SUMMARY_SAVE_RESET = " SUMMARY_SAVE_RESET";

export const SIZEWEIGHTGROUP_UPDATE_REQUEST = "SIZEWEIGHTGROUP_UPDATE_REQUEST";
export const SIZEWEIGHTGROUP_UPDATE_SUCCESS = "SIZEWEIGHTGROUP_UPDATE_SUCCESS";
export const SIZEWEIGHTGROUP_UPDATE_FAIL = "SIZEWEIGHTGROUP_UPDATE_FAIL";
export const SIZEWEIGHTGROUP_UPDATE_RESET = "SIZEWEIGHTGROUP_UPDATE_RESET";

export const SIZEWEIGHTGROUP_LIST_REQUEST = "SIZEWEIGHTGROUP_LIST_REQUEST";
export const SIZEWEIGHTGROUP_LIST_SUCCESS = "SIZEWEIGHTGROUP_LIST_SUCCESS";
export const SIZEWEIGHTGROUP_LIST_FAIL = "SIZEWEIGHTGROUP_LIST_FAIL";
export const SIZEWEIGHTGROUP_LIST_RESET = "SIZEWEIGHTGROUP_LIST_RESET";

export const SUMMARY_LIST_REQUEST = " SUMMARY_LIST_REQUEST";
export const SUMMARY_LIST_SUCCESS = " SUMMARY_LIST_SUCCESS";
export const SUMMARY_LIST_FAIL = " SUMMARY_LIST_FAIL";
export const SUMMARY_LIST_RESET = " SUMMARY_LIST_RESET";

export const SIZEWEIGHTGROUP_ALLLIST_REQUEST =
  "SIZEWEIGHTGROUP_ALLLIST_REQUEST";
export const SIZEWEIGHTGROUP_ALLLIST_SUCCESS =
  "SIZEWEIGHTGROUP_ALLLIST_SUCCESS";
export const SIZEWEIGHTGROUP_ALLLIST_FAIL = "SIZEWEIGHTGROUP_ALLLIST_FAIL";
export const SIZEWEIGHTGROUP_ALLLIST_RESET = "SIZEWEIGHTGROUP_ALLLIST_RESET";

export const SUMMARY_UPDATE_REQUEST = " SUMMARY_UPDATE_REQUEST";
export const SUMMARY_UPDATE_SUCCESS = " SUMMARY_UPDATE_SUCCESS";
export const SUMMARY_UPDATE_FAIL = " SUMMARY_UPDATE_FAIL";
export const SUMMARY_UPDATE_RESET = " SUMMARY_UPDATE_RESET";
