export const SPECIFIC_PRICE_CONDITION_REQUEST = "SPECIFIC_PRICE_CONDITION_REQUEST";
export const SPECIFIC_PRICE_CONDITION_SUCCESS = "SPECIFIC_PRICE_CONDITION_SUCCESS";
export const SPECIFIC_PRICE_CONDITION_FAIL = "SPECIFIC_PRICE_CONDITION_FAIL";
export const SPECIFIC_PRICE_CONDITION_RESET = "SPECIFIC_PRICE_CONDITION_RESET";

export const PRODUCT_LIST_GRID_REQUEST = "PRODUCT_LIST_GRID_REQUEST";
export const PRODUCT_LIST_GRID_SUCCESS = "PRODUCT_LIST_GRID_SUCCESS";
export const PRODUCT_LIST_GRID_FAIL = "PRODUCT_LIST_GRID_FAIL";
export const PRODUCT_LIST_GRID_RESET = "PRODUCT_LIST_GRID_RESET";

export const SPECIFIC_DELETE_REQUEST = "SPECIFIC_DELETE_REQUEST";
export const SPECIFIC_DELETE_SUCCESS = "SPECIFIC_DELETE_SUCCESS";
export const SPECIFIC_DELETE_FAIL = "SPECIFIC_DELETE_FAIL";
export const SPECIFIC_DELETE_RESET = "SPECIFIC_DELETE_RESET";

export const SPECIFIC_UPDATE_REQUEST = "SPECIFIC_UPDATE_REQUEST";
export const SPECIFIC_UPDATE_SUCCESS = "SPECIFIC_UPDATE_SUCCESS";
export const SPECIFIC_UPDATE_FAIL = "SPECIFIC_UPDATE_FAIL";
export const SPECIFIC_UPDATE_RESET = "SPECIFIC_UPDATE_RESET";


export const SPECIFIC_PRICE_LIST_REQUEST = "SPECIFIC_PRICE_LIST_REQUEST";
export const SPECIFIC_PRICE_LIST_SUCCESS = "SPECIFIC_PRICE_LIST_SUCCESS";
export const SPECIFIC_PRICE_LIST_FAIL = "SPECIFIC_PRICE_LIST_FAIL";
export const SPECIFIC_PRICE_LIST_RESET = "SPECIFIC_PRICE_LIST_RESET";