export const STATE_SAVE_REQUEST = " STATE_SAVE_REQUEST";
export const STATE_SAVE_SUCCESS = " STATE_SAVE_SUCCESS";
export const STATE_SAVE_FAIL = " STATE_SAVE_FAIL";
export const STATE_SAVE_RESET = " STATE_SAVE_RESET";

export const STATE_LIST_REQUEST = " STATE_LIST_REQUEST";
export const STATE_LIST_SUCCESS = " STATE_LIST_SUCCESS";
export const STATE_LIST_FAIL = " STATE_LIST_FAIL";
export const STATE_LIST_RESET = " STATE_LIST_RESET";

export const STATE_UPDATE_REQUEST = " STATE_UPDATE_REQUEST";
export const STATE_UPDATE_SUCCESS = " STATE_UPDATE_SUCCESS";
export const STATE_UPDATE_FAIL = " STATE_UPDATE_FAIL";
export const STATE_UPDATE_RESET = " STATE_UPDATE_RESET";

export const STATE_DELETE_REQUEST = " STATE_DELETE_REQUEST";
export const STATE_DELETE_SUCCESS = " STATE_DELETE_SUCCESS";
export const STATE_DELETE_FAIL = " STATE_DELETE_FAIL";
export const STATE_DELETE_RESET = " STATE_DELETE_RESET";

export const STATE_ENABLE_REQUEST = " STATE_ENABLE_REQUEST";
export const STATE_ENABLE_SUCCESS = " STATE_ENABLE_SUCCESS";
export const STATE_ENABLE_FAIL = " STATE_ENABLE_FAIL";
export const STATE_ENABLE_RESET = " STATE_ENABLE_RESET";

export const STATE_CHECKBOX_REQUEST = " STATE_CHECKBOX_REQUEST";
export const STATE_CHECKBOX_SUCCESS = " STATE_CHECKBOX_SUCCESS";
export const STATE_CHECKBOX_FAIL = " STATE_CHECKBOX_FAIL";
export const STATE_CHECKBOX_RESET = " STATE_CHECKBOX_RESET";

export const STATE_BULKDELETE_REQUEST = " STATE_BULKDELETE_REQUEST";
export const STATE_BULKDELETE_SUCCESS = " STATE_BULKDELETE_SUCCESS";
export const STATE_BULKDELETE_FAIL = " STATE_BULKDELETE_FAIL";
export const STATE_BULKDELETE_RESET = " STATE_BULKDELETE_RESET";

export const STATE_ZONEASSIGHN_REQUEST = " STATE_ZONEASSIGHN_REQUEST";
export const STATE_ZONEASSIGHN_SUCCESS = " STATE_ZONEASSIGHN_SUCCESS";
export const STATE_ZONEASSIGHN_FAIL = " STATE_ZONEASSIGHN_FAIL";
export const STATE_ZONEASSIGHN_RESET = " STATE_ZONEASSIGHN_RESET";
