export const TAXES_CREATE_REQUEST = 'TAXES_CREATE_REQUEST';
export const TAXES_CREATE_SUCCESS = 'TAXES_CREATE_SUCCESS';
export const TAXES_CREATE_FAIL = 'TAXES_CREATE_FAIL';
export const TAXES_CREATE_RESET = 'TAXES_CREATE_RESET';

export const TAXES_LIST_REQUEST = 'TAXES_LIST_REQUEST';
export const TAXES_LIST_SUCCESS = 'TAXES_LIST_SUCCESS';
export const TAXES_LIST_FAIL = 'TAXES_LIST_FAIL';
export const TAXES_LIST_RESET = 'TAXES_LIST_RESET';

export const TAXES_MASTER_DEL_REQUEST = 'TAXES_MASTER_DEL_REQUEST';
export const TAXES_MASTER_DEL_SUCCESS = 'TAXES_MASTER_DEL_SUCCESS';
export const TAXES_MASTER_DEL_FAIL = 'TAXES_MASTER_DEL_FAIL';
export const TAXES_MASTER_DEL_RESET = 'TAXES_MASTER_DEL_RESET';

export const TAXES_MASTER_UPDATE_REQUEST = 'TAXES_MASTER_UPDATE_REQUEST';
export const TAXES_MASTER_UPDATE_SUCCESS = 'TAXES_MASTER_UPDATE_SUCCESS';
export const TAXES_MASTER_UPDATE_FAIL = 'TAXES_MASTER_UPDATE_FAIL';
export const TAXES_MASTER_UPDATE_RESET = 'TAXES_MASTER_UPDATE_RESET';

export const TAXES_UPDATES_REQUEST = 'TAXES_UPDATES_REQUEST';
export const TAXES_UPDATES_SUCCESS = 'TAXES_UPDATES_SUCCESS';
export const TAXES_UPDATES_FAIL = 'TAXES_UPDATES_FAIL';
export const TAXES_UPDATES_RESET = 'TAXES_UPDATES_RESET';

export const TAXES_MULTIPLE_DELETE_REQUEST = 'TAXES_MULTIPLE_DELETE_REQUEST';
export const TAXES_MULTIPLE_DELETE_SUCCESS = 'TAXES_MULTIPLE_DELETE_SUCCESS';
export const TAXES_MULTIPLE_DELETE_FAIL = 'TAXES_MULTIPLE_DELETE_FAIL';
export const TAXES_MULTIPLE_DELETE_RESET = 'TAXES_MULTIPLE_DELETE_RESET';

export const TAXES_ENABLE_REQUEST = 'TAXES_ENABLE_REQUEST';
export const TAXES_ENABLE_SUCCESS = 'TAXES_ENABLE_SUCCESS';
export const TAXES_ENABLE_FAIL = 'TAXES_ENABLE_FAIL';
export const TAXES_ENABLE_RESET = 'TAXES_ENABLE_RESET';
