export const ZONE_SAVE_REQUEST = "ZONE_SAVE_REQUEST";
export const ZONE_SAVE_SUCCESS = "ZONE_SAVE_SUCCESS";
export const ZONE_SAVE_FAIL = "ZONE_SAVE_FAIL";
export const ZONE_SAVE_RESET = "ZONE_SAVE_RESET";

export const ZONE_LIST_REQUEST = "ZONE_LIST_REQUEST";
export const ZONE_LIST_SUCCESS = "ZONE_LIST_SUCCESS";
export const ZONE_LIST_FAIL = "ZONE_LIST_FAIL";

export const ZONE_UPDATE_REQUEST = "ZONE_UPDATE_REQUEST";
export const ZONE_UPDATE_SUCCESS = "ZONE_UPDATE_SUCCESS";
export const ZONE_UPDATE_FAIL = "ZONE_UPDATE_FAIL";
export const ZONE_UPDATE_RESET = "ZONE_UPDATE_RESET";

export const ZONE_DELETE_REQUEST = "ZONE_DELETE_REQUEST";
export const ZONE_DELETE_SUCCESS = "ZONE_DELETE_SUCCESS";
export const ZONE_DELETE_FAIL = "ZONE_DELETE_FAIL";
export const ZONE_DELETE_RESET = "ZONE_DELETE_RESET";

export const ZONE_ENABLE_REQUEST = "ZONE_ENABLE_REQUEST";
export const ZONE_ENABLE_SUCCESS = "ZONE_ENABLE_SUCCESS";
export const ZONE_ENABLE_FAIL = "ZONE_ENABLE_FAIL";
export const ZONE_ENABLE_RESET = "ZONE_ENABLE_RESET";

export const ZONE_CHECKBOX_REQUEST = " ZONE_CHECKBOX_REQUEST";
export const ZONE_CHECKBOX_SUCCESS = " ZONE_CHECKBOX_SUCCESS";
export const ZONE_CHECKBOX_FAIL = " ZONE_CHECKBOX_FAIL";
export const ZONE_CHECKBOX_RESET = " ZONE_CHECKBOX_RESET";

export const ZONE_BULKDELETE_REQUEST = " ZONE_BULKDELETE_REQUEST";
export const ZONE_BULKDELETE_SUCCESS = " ZONE_BULKDELETE_SUCCESS";
export const ZONE_BULKDELETE_FAIL = " ZONE_BULKDELETE_FAIL";
export const ZONE_BULKDELETE_RESET = " ZONE_BULKDELETE_RESET";
