import { applyMiddleware, combineReducers, compose, createStore } from "redux";
import thunk from "redux-thunk";
import {
  AddressListReducer,
  addressListReducer,
} from "./reducers/addressReducers";
import {
  cartDeleteReducer,
  cartReducer,
  cartReducerItems,
  cartUpdateReducer,
  userCartListReducer,
} from "./reducers/cartReducers";
import {
  orderCreateReducer,
  orderDeleteReducer,
  orderDeliverReducer,
  orderDetailsReducer,
  orderListReducer,
  orderMineListReducer,
  orderPayReducer,
  orderSummaryReducer,
  UpdatedatagridReducer,
} from "./reducers/orderReducers";
import {
  productCategorygroupListReducer,
  productCategoryListReducer,
  productCategorytypeListReducer,
  productCreateReducer,
  productDeleteReducer,
  productDetailsReducer,
  productKidsListReducer,
  productListReducer,
  productMenListReducer,
  productReviewCreateReducer,
  productUpdateReducer,
  productWomenListReducer,
} from "./reducers/productReducers";
import { SareeDetailsReducer, SareeListReducer } from "./reducers/sareeReducer";
import {
  userAccountcreationReducer,
  userAccountReducer,
  userAddressMapReducer,
  userAdmininReducer,
  userDeleteReducer,
  userDetailsReducer,
  userListReducer,
  userRegisterReducer,
  userSigninReducer,
  userTopSellerListReducer,
  userUpdateProfileReducer,
  userUpdateReducer,
} from "./reducers/userReducers";
import {
  womenCategoryListReducer,
  womenCreateReducer,
  womenDeleteReducer,
  womenDetailsReducer,
  womenListReducer,
  womenReviewCreateReducer,
  womenUpdateReducer,
} from "./reducers/womenReducers";
// import { cartWomenReducer } from './reducers/cartWomenReducers';
import { updateShippingSize } from "./actions/SizeWeightGroupAction";
import {
  appEnableUpdateReducer,
  applicationDeleteReducer,
  applicationSettingReducer,
  appSettingListReducer,
} from "./reducers/applicationReducer";
import {
  AttEnableUpdateReducer,
  attributeActiveReducer,
  AttributeCreateReducer,
  attributeDeleteReducer,
  AttributeMasterListReducer,
  AttributemultipleDeleteReducer,
  attributeUpdateReducer,
  AttributeValueallListReducer,
  AttributeValueCreateReducer,
  attributeValueDeleteReducer,
  AttributeValueListReducer,
  attributeValueUpdateReducer,
  attvalueActiveReducer,
  AttValueDeleteReducer,
  AttValueEnableUpdateReducer,
  featureActiveReducer,
  featureDeleteReducer,
  featureEnableUpdateReducer,
  FeaturemutiDeleteReducer,
  FeaturesCreateReducer,
  FeaturesListReducer,
  FeaturesValueCreateReducer,
  FeaturesValueListReducer,
  featurevalueActiveReducer,
  featureValueDeleteReducer,
  featurevalueEnableUpdateReducer,
  feautureUpdateReducer,
  feautureValueUpdateReducer,
  FvalueDeleteReducer,
} from "./reducers/AttributeReducers";
import {
  brandAddressDeleteReducer,
  brandAddressListReducer,
  brandAddressReducer,
  brandAddressUpdateReducer,
  brandCheckboxReducer,
  brandDeleteReducer,
  brandListReducer,
  BrandmultipleDeleteReducer,
  brandReducer,
  brandUpdateReducer,
  EnablebrandUpdateReducer,
} from "./reducers/brandReducer";
import {
  categmastercreateReducer,
  categoryCheckboxReducer,
  categoryChildAllListReducer,
  categorychildReucer,
  categoryChilNewListReducer,
  categorygrandChildListReducer,
  categorygrandChildNewListReducer,
  categoryGrandchildReucer,
  categoryMasterallListReducer,
  CategoryMasterDeleteReducer,
  categorymasterReducer,
  ChildcategoryCheckboxReducer,
  childDeleteReducer,
  EnableChildReducer,
  EnablegrandChildReducer,
  EnableParentReducer,
  grandChildcategoryCheckboxReducer,
  grandDeleteReducer,
  parentDeleteReducer,
} from "./reducers/categoryMasterReducer";
import {
  categoryCreateReducer,
  categoryListReducer,
  categorymasterCreateReducer,
  categoryMasterListReducer,
  childcategoryCreateReducer,
  ChildCategoryListReducer,
  subcategoryCreateReducer,
  subCategoryListReducer,
} from "./reducers/categoryReducers";
import {
  cataloglastProdReducer,
  catalogProdReducer,
  catalogProdUpdateReducer,
  catalogProdViewReducer,
  catComReducer,
  catProddeleteReducer,
  catProdDetailReducer,
  catProductReducer,
  CombinationchildListReducer,
  CombinationListReducer,
  EnableproductUpdateReducer,
  ProductActiveReducer,
  ProductmultipleDeleteReducer,
  wishListUpdateReducer,
} from "./reducers/catProductReducer";
import {
  activeCityReducer,
  cityCheckboxReducer,
  CityDeleteReducer,
  CityListReducer,
  CitymultipleDeleteReducer,
  CitySaveReducer,
  CityUpdateReducer,
  cityZoneCheckboxReducer,
} from "./reducers/CityReducer";
import {
  ComboDeleteReducer,
  ComboSaveReducer,
  ComboTaxReducer,
  ComboUpdateReducer,
} from "./reducers/ComboReducer";
import {
  countryCheckboxReducer,
  CountryEnableReducer,
  CountryListReducer,
  CountryMasterDeleteReducer,
  CountrymultipleDeleteReducer,
  CountrySaveReducer,
  CountryUpdateReducer,
} from "./reducers/CountryReducers";
import {
  customAddDeleteReducer,
  customAddListReducer,
  customAddressUpdateReducer,
  customerAddressReducer,
} from "./reducers/customerReducer";
import {
  activeCustomerEnableReducer,
  CusmultipleDeleteReducer,
  CusomerDeleteReducer,
  CustomerBulkEnableReducer,
  CustomerListReducer,
  CustomerSaveReducer,
  CustomerUpdateReducer,
} from "./reducers/customerrReducers";
import {
  EmployeeActiveReducer,
  EmployeeDeleteReducer,
  EmployeeListReducer,
  EmployeemultipleDeleteReducer,
  EmployeeProfileListReducer,
  EmployeeSaveReducer,
  EmployeeUpdateReducer,
  EnableUpdateReducer,
  profileDeleteReducer,
  ProfileUpdateReducer,
} from "./reducers/EmployeeReducers";
import {
  GeneralallListReducer,
  generalCheckboxReducer,
  GeneralEnableReducer,
  GeneralListReducer,
  generalMasterDeleteReducer,
  GeneralmultipleDeleteReducer,
  GeneralSaveReducer,
  GeneralStatusEnableReducer,
  generalUpdateReducer,
} from "./reducers/GeneralReducers";
import {
  kidCategoryListReducer,
  kidCreateReducer,
  kidDeleteReducer,
  kidDetailsReducer,
  kidListReducer,
  kidReviewCreateReducer,
  kidUpdateReducer,
} from "./reducers/kidReducer";
import {
  OptionListReducer,
  OptionSaveReducer,
  OptionUpdateReducer,
} from "./reducers/OptionReducer";
import { otpListReducer, userOtpReducer } from "./reducers/otpReducer";
import {
  activePayReducer,
  payCheckboxReducer,
  PayDeleteReducer,
  PayListReducer,
  PaymentSaveReducer,
  PaymultipleDeleteReducer,
  PayUpdateReducer,
} from "./reducers/PayReducer";
import { enquiryDeleteReducer, notificationClearallReducer, notificationDeleteReducer, productEnquiryListReducer, productNotificationListReducer } from "./reducers/prodEnquiryReducer";
import {
  PriceFindOneListReducer,
  PriceLastListReducer,
  PriceListReducer,
  PricingDetailsReducer,
  PricingUpdateReducer,
} from "./reducers/prodReducer";
import {
  QuantitiesSaveReducer,
  QuantityFindOneReducer,
  QuantityLastListReducer,
  QuantityListReducer,
  QuantityUpdateReducer,
} from "./reducers/ProductQtyReducer";
import {
  ShipListReducer,
  shippingSaveReducer,
  ShipUpdateReducer,
} from "./reducers/ProductShippingReducer";
import {
  SeoListReducer,
  seoReducer,
  SeoUpdateReducer,
} from "./reducers/seoReducer";
import {
  ShippingAllListReducer,
  ShippingcostReducer,
  shippingReducer,
  shippingUpdatesReducer,
} from "./reducers/shippingLocReducers";
import {
  ShippingAlllListReducer,
  ShippingListReducer,
  ShippingSaveReducer,
} from "./reducers/SizeWeightGroupReducer";
import {
  SpecificDeleteReducer,
  specificPriceReducer,
  specificPriceUpdateReducer,
  speciPriceGridListReducer,
  speciPriceListReducer,
} from "./reducers/specificPriceReducer";
import {
  activeStateReducer,
  StateDeleteReducer,
  StateListReducer,
  StatemultipleDeleteReducer,
  StateSaveReducer,
  statesCheckboxReducer,
  statesZoneCheckboxReducer,
  StateUpdateReducer,
} from "./reducers/StateReducer";
import {
  SummaryListReducer,
  SummarySaveReducer,
  SummaryUpdateReducer,
} from "./reducers/SummaryReducer";
import {
  TaxEnableReducer,
  taxesCheckboxReducer,
  TaxesCreateReducer,
  TaxesListReducer,
  TaxesMasterDeleteReducer,
  TaxesUpdateReducer,
  TaxmultipleDeleteReducer,
} from "./reducers/taxesReducer";
import {
  activeZoneReducer,
  ZoneCheckboxReducer,
  ZoneDeleteReducer,
  ZoneListReducer,
  ZonemultipleDeleteReducer,
  ZoneSaveReducer,
  ZoneUpdateReducer,
} from "./reducers/ZoneReducers";
import {
  StatusDeleteReducer,
  StatusListReducer,
} from "./reducers/StatusReducer";

// import { cartKidReducer } from './reducers/cartKidReducers';
// import { suitDetailsReducer, suitListReducer, suitReviewCreateReducer } from './reducers/suitReducers';
// import { cartKidReducer } from './reducers/cartKidReducers';
// import { cartWomenReducer } from './reducers/cartWomenReducers';

const initialState = {
  userSignin: {
    userInfo: localStorage.getItem("userInfo")
      ? JSON.parse(localStorage.getItem("userInfo"))
      : null,
  },

  userAccount: {
    accountInfo: localStorage.getItem("data")
      ? JSON.parse(localStorage.getItem("data"))
      : null,
  },
  userAccountCreation: {
    accountcreationInfo: localStorage.getItem("accountcreationInfo")
      ? JSON.parse(localStorage.getItem("accountcreationInfo"))
      : null,
  },
  userAdminin: {
    adminInfo: localStorage.getItem("adminInfo")
      ? JSON.parse(localStorage.getItem("adminInfo"))
      : null,
  },
  cart: {
    cartItems: localStorage.getItem("usercart")
      ? JSON.parse(localStorage.getItem("usercart"))
      : [],
    shippingAddress: localStorage.getItem("shippingAddress")
      ? JSON.parse(localStorage.getItem("shippingAddress"))
      : {},
    paymentMethod: "PayPal",
  },
};

const reducer = combineReducers({
  addressesList: addressListReducer,
  productList: productListReducer,
  productMenList: productMenListReducer,
  productWomenList: productWomenListReducer,
  productKidsList: productKidsListReducer,
  womenList: womenListReducer,
  userCartListItem: userCartListReducer,
  cartItems: cartReducerItems,
  cartDelete: cartDeleteReducer,
  cartUpdate: cartUpdateReducer,
  kidList: kidListReducer,
  applicationCreate: applicationSettingReducer,
  brandCreate: brandReducer,
  brandReduce: brandListReducer,
  brandAddressCreate: brandAddressReducer,
  brandAddreList: brandAddressListReducer,
  brandUpdate: brandUpdateReducer,
  brandDelete: brandDeleteReducer,
  brandAddressDelete: brandAddressDeleteReducer,
  brandAddressUpdate: brandAddressUpdateReducer,
  catProductSave: catProductReducer,
  catalogProd: catalogProdReducer,
  catalogProdUpdate: catalogProdUpdateReducer,
  catProddelete: catProddeleteReducer,
  catProdDetail: catProdDetailReducer,
  wishListUpdate: wishListUpdateReducer,
  applicationList: appSettingListReducer,
  userOtp: userOtpReducer,
  otpLists: otpListReducer,

  productDetails: productDetailsReducer,
  womenDetails: womenDetailsReducer,

  kidDetails: kidDetailsReducer,
  cart: cartReducer,

  // cart: cartWomenReducer,
  AttributeCreate: AttributeCreateReducer,
  attributeMasterList: AttributeMasterListReducer,
  AttributeValueCreate: AttributeValueCreateReducer,
  AttributeValueList: AttributeValueListReducer,
  FeaturesCreate: FeaturesCreateReducer,
  FeaturesList: FeaturesListReducer,
  CreateFeaturesValue: FeaturesValueCreateReducer,
  FeaturesValueList: FeaturesValueListReducer,
  attributeUpdate: attributeUpdateReducer,
  attributeDelete: attributeDeleteReducer,
  attributeValueUpdate: attributeValueUpdateReducer,
  attributeValueDelete: attributeValueDeleteReducer,
  feautureUpdate: feautureUpdateReducer,
  feautureValueUpdate: feautureValueUpdateReducer,
  featureDelete: featureDeleteReducer,
  featureValueDelete: featureValueDeleteReducer,
  // cart: cartKidReducer,
  userSignin: userSigninReducer,
  userAccount: userAccountReducer,
  productEnquiryList: productEnquiryListReducer,
  productEnquirydel: enquiryDeleteReducer,
  notificationall: productNotificationListReducer,
  notificationdel: notificationDeleteReducer,
  notificationclearall: notificationClearallReducer,
  customer: customerAddressReducer,
  customAddressList: customAddListReducer,
  customAddressUpdate: customAddressUpdateReducer,
  customAddDelete: customAddDeleteReducer,

  categoryList: categoryListReducer,
  childcategory: childcategoryCreateReducer,
  ChildCategoryLis: ChildCategoryListReducer,
  subcategoryCreate: subcategoryCreateReducer,
  subCategoryList: subCategoryListReducer,
  categoryMasterList: categoryMasterListReducer,
  categoryMasterCreate: categorymasterCreateReducer,
  categoryCreate: categoryCreateReducer,
  userAccountCreation: userAccountcreationReducer,
  userAdminin: userAdmininReducer,
  userRegister: userRegisterReducer,
  orderCreate: orderCreateReducer,
  orderDetails: orderDetailsReducer,
  orderPay: orderPayReducer,
  orderMineList: orderMineListReducer,
  userDetails: userDetailsReducer,
  userUpdateProfile: userUpdateProfileReducer,
  productCreate: productCreateReducer,
  womenCreate: womenCreateReducer,
  kidCreate: kidCreateReducer,
  productUpdate: productUpdateReducer,
  womenUpdate: womenUpdateReducer,
  kidUpdate: kidUpdateReducer,
  productDelete: productDeleteReducer,
  womenDelete: womenDeleteReducer,
  kidDelete: kidDeleteReducer,
  orderList: orderListReducer,
  orderDelete: orderDeleteReducer,
  orderDeliver: orderDeliverReducer,
  userList: userListReducer,
  userUpdate: userUpdateReducer,
  userDelete: userDeleteReducer,
  userTopSellersList: userTopSellerListReducer,
  productCategoryList: productCategoryListReducer,
  productCategorygroupList: productCategorygroupListReducer,
  productCategorytypeList: productCategorytypeListReducer,
  womenCategoryList: womenCategoryListReducer,
  kidCategoryList: kidCategoryListReducer,
  productReviewCreate: productReviewCreateReducer,
  womenReviewCreate: womenReviewCreateReducer,
  kidReviewCreate: kidReviewCreateReducer,
  userAddressMap: userAddressMapReducer,
  orderSummary: orderSummaryReducer,
  sareeReducer: SareeListReducer,
  sareeDetails: SareeDetailsReducer,
  CategoryMasterCreate: categmastercreateReducer,
  CategoryMasterallList: categoryMasterallListReducer,
  categoryChildAll: categoryChildAllListReducer,
  categoryChilNew: categoryChilNewListReducer,
  categorygrandChild: categorygrandChildNewListReducer,
  categorygrandChildList: categorygrandChildListReducer,
  CategoryMasterDelete: CategoryMasterDeleteReducer,
  CategoryMasterUpdate: categorymasterReducer,
  categoryCheckbox: categoryCheckboxReducer,
  ChildcategoryCheckbox: ChildcategoryCheckboxReducer,
  grandChildcategoryCheckbox: grandChildcategoryCheckboxReducer,
  brandCheckbox: brandCheckboxReducer,
  CombinationList: CombinationListReducer,
  Combinationchild: CombinationchildListReducer,
  EmployeeProfile: EmployeeProfileListReducer,
  EmployeeList: EmployeeListReducer,
  EmployeeUpdate: EmployeeUpdateReducer,
  EmployeeDelete: EmployeeDeleteReducer,
  ProfileUpdate: ProfileUpdateReducer,
  profileDelete: profileDeleteReducer,
  attributeActive: attributeActiveReducer,
  featurevalueActive: featurevalueActiveReducer,
  featureActive: featureActiveReducer,
  attvalueActive: attvalueActiveReducer,
  EmployeeActive: EmployeeActiveReducer,
  ProductActive: ProductActiveReducer,
  catCom: catComReducer,
  EmployeeSave: EmployeeSaveReducer,
  EnableUpdate: EnableUpdateReducer,
  AttEnableUpdate: AttEnableUpdateReducer,
  AttValueEnable: AttValueEnableUpdateReducer,
  featureEnable: featureEnableUpdateReducer,
  featurevalueEnable: featurevalueEnableUpdateReducer,
  Enablebrand: EnablebrandUpdateReducer,
  Enableproduct: EnableproductUpdateReducer,
  EnableParent: EnableParentReducer,
  EnableChild: EnableChildReducer,
  EnablegrandChild: EnablegrandChildReducer,
  Employeemultiple: EmployeemultipleDeleteReducer,
  Attributemultiple: AttributemultipleDeleteReducer,
  AttValueDelete: AttValueDeleteReducer,
  FeaturemutiDelete: FeaturemutiDeleteReducer,
  FvalueDelete: FvalueDeleteReducer,
  Brandmultiple: BrandmultipleDeleteReducer,
  Productmultiple: ProductmultipleDeleteReducer,
  parentDelete: parentDeleteReducer,
  childDelete: childDeleteReducer,
  grandDelete: grandDeleteReducer,
  applicationDelete: applicationDeleteReducer,
  appEnable: appEnableUpdateReducer,
  customerSave: CustomerSaveReducer,
  customerList: CustomerListReducer,
  customerUpdate: CustomerUpdateReducer,
  customerDelete: CusomerDeleteReducer,
  customerEnable: activeCustomerEnableReducer,
  customerbulken: CustomerBulkEnableReducer,
  customerBulkDel: CusmultipleDeleteReducer,
  QuantitiesSave: QuantitiesSaveReducer,
  ShippingSave: shippingSaveReducer,
  seoSave: seoReducer,
  PricingDetails: PricingDetailsReducer,
  specificPrice: specificPriceReducer,
  taxesCreate: TaxesCreateReducer,
  taxesList: TaxesListReducer,
  specificGrid: speciPriceGridListReducer,
  SpecificDelete: SpecificDeleteReducer,
  SpecificUpdate: specificPriceUpdateReducer,
  mastertax: TaxesMasterDeleteReducer,
  updatetax: TaxesUpdateReducer,
  ComboSave: ComboSaveReducer,
  ComboUpdate: ComboUpdateReducer,
  ComboDelete: ComboDeleteReducer,
  optionSave: OptionSaveReducer,
  taxesCheckbox: taxesCheckboxReducer,
  taxmultiple: TaxmultipleDeleteReducer,
  comboTax: ComboTaxReducer,
  childCategoryUpdate: categorychildReucer,
  grandChildCategoryUpdate: categoryGrandchildReucer,
  TaxEnables: TaxEnableReducer,
  generalsave: GeneralSaveReducer,
  generallist: GeneralListReducer,
  sizeweightgroup: ShippingSaveReducer,
  sizeweightgrouplist: ShippingListReducer,
  generalallalllist: GeneralallListReducer,
  generalupdate: generalUpdateReducer,
  summarySave: SummarySaveReducer,
  summaryList: SummaryListReducer,
  SummaryUpdate: SummaryUpdateReducer,
  shippinglist: shippingReducer,
  ShippingviewList: ShippingcostReducer,
  freeShippingUpdate: shippingUpdatesReducer,
  shippingSizeUpdate: updateShippingSize,
  shiploccostallList: ShippingAllListReducer,
  ShipAllList: ShippingAlllListReducer,
  generalDelete: generalMasterDeleteReducer,
  generalCheckbox: generalCheckboxReducer,
  GeneralEnable: GeneralEnableReducer,
  Generalmuldelete: GeneralmultipleDeleteReducer,
  GeneralStatusEnable: GeneralStatusEnableReducer,
  CountrySave: CountrySaveReducer,
  CountryList: CountryListReducer,
  CountryUpdate: CountryUpdateReducer,
  CountryMasterDelete: CountryMasterDeleteReducer,
  CountryEnable: CountryEnableReducer,
  ZoneSave: ZoneSaveReducer,
  ZoneList: ZoneListReducer,
  ZoneDelete: ZoneDeleteReducer,
  ZoneUpdate: ZoneUpdateReducer,
  ZoneEnable: activeZoneReducer,
  ZoneCheckbox: ZoneCheckboxReducer,
  ZoneBulkDelete: ZonemultipleDeleteReducer,
  StateSave: StateSaveReducer,
  StateList: StateListReducer,
  StateUpdate: StateUpdateReducer,
  StateDelete: StateDeleteReducer,
  StateEnable: activeStateReducer,
  StateCheckBox: statesCheckboxReducer,
  StateBulkDelete: StatemultipleDeleteReducer,
  StateZone: statesZoneCheckboxReducer,
  CitySave: CitySaveReducer,
  CityList: CityListReducer,
  CityUpdate: CityUpdateReducer,
  CityDelete: CityDeleteReducer,
  CityEnable: activeCityReducer,
  CityCheckBox: cityCheckboxReducer,
  CityMultipleDelete: CitymultipleDeleteReducer,
  CityZone: cityZoneCheckboxReducer,
  countryCheckbox: countryCheckboxReducer,
  CountrymultipleDelete: CountrymultipleDeleteReducer,
  PaymentSave: PaymentSaveReducer,
  PaymentList: PayListReducer,
  PaymentUpdate: PayUpdateReducer,
  PaymentDelete: PayDeleteReducer,
  Paymenten: activePayReducer,
  paybulkenable: payCheckboxReducer,
  payDelete: PaymultipleDeleteReducer,
  QuantityUpdate: QuantityUpdateReducer,
  catalogProdView: catalogProdViewReducer,
  ShipUpdate: ShipUpdateReducer,
  QuantityList: QuantityListReducer,
  ShipList: ShipListReducer,
  PriceList: PriceListReducer,
  PricingUpdate: PricingUpdateReducer,
  speciPriceList: speciPriceListReducer,
  SeoList: SeoListReducer,
  SeoUpdate: SeoUpdateReducer,
  OptionList: OptionListReducer,
  OptionUpdate: OptionUpdateReducer,
  statuslist: StatusListReducer,
  AddressList: AddressListReducer,
  allatt: AttributeValueallListReducer,
  updatedatagrid: UpdatedatagridReducer,
  statusDlete: StatusDeleteReducer,
  QuantityLastList: QuantityLastListReducer,
  PriceLastList: PriceLastListReducer,
  QuantityFindOne: QuantityFindOneReducer,
  PriceFindOneList: PriceFindOneListReducer,
  cataloglastProd: cataloglastProdReducer,
});
const composeEnhancer = window.__REDUX_DEVTOOLS_EXTENSION_COMPOSE__ || compose;
const store = createStore(
  reducer,
  initialState,
  composeEnhancer(applyMiddleware(thunk))
);
document.cookie = "name=sri";
export default store;
